.travis.yml, README.md, cmake-scripts/libusrsctp-CMakeLists.txt
=> Add .travis.yml

samples/Common.c, samples/Samples.h, samples/gstSample.h, samples/kvsWebRTCClientMasterGstreamerSample.c, src/source/PeerConnection/JitterBuffer.c, src/source/Rtp/Codecs/RtpH264Payloader.c, src/source/Rtp/Codecs/RtpH264Payloader.h, src/source/Rtp/Codecs/RtpVP8Payloader.c, tst/RtpFunctionalityTest.cpp
* Minor fix for vp8 depayload
* Fix h264 depay for aggregated packets
* Use gstreamer to play received audio
=> Update from internal

.travis.yml, CMakeLists.txt, tst/JitterBufferFunctionalityTest.cpp, tst/SdpApiTest.cpp, tst/SignalingApiTest.cpp
=> Add ADDRESS_SANITIZIER to CMakeLists

src/source/Dtls/Dtls.c
Chromium is unable to find intersection
=> Don't exclude SSLv3 Ciphers

.travis.yml, CMakeLists.txt
UBSAN and TSAN don't fail the build yet, lots of things to fix
=> Add MSAN, TSAN, UBSAN

src/source/PeerConnection/SessionDescription.c, src/source/Sdp/Deserialize.c
* SDP Deserialize now properly handles Media ConnectionInformation
* Don't set Reduced Size RTCP attribute. We don't emit RTCP at all currently
Resolves #26
=> Fix FireFox compatibility issues

.travis.yml
Fixes .travis.yml linter error
=> Move allow_failures entry into matrix

src/source/Ice/IceUtils.c, tst/IceFunctionalityTest.cpp
add ice unit test for pruneUnconnectedIceCandidatePair
=> add ice unit test

src/source/PeerConnection/PeerConnection.c, src/source/Sctp/Sctp.c, tst/PeerConnectionFunctionalityTest.cpp, tst/SrtpApiTest.cpp, tst/WebRTCClientTestFixture.cpp
Connect two PeerConnections and shutdown as soon as ICE goes to connected
=> Add PeerConnection integration test

.travis.yml, src/include/com/amazonaws/kinesis/video/webrtcclient/Include.h, src/source/Ice/IceAgent.h, src/source/Ice/IceUtils.h, src/source/Ice/SocketConnection.h, src/source/Include_i.h
*Description of changes:* 
1. Check if we can add old version of gcc to travis build.
2. Add fix for the build failure.
=> Add gcc 4.4 build to travis

.travis.yml, src/source/Ice/IceAgent.c, src/source/Ice/Network.c, src/source/PeerConnection/SessionDescription.c, src/source/PeerConnection/SessionDescription.h, tst/PeerConnectionFunctionalityTest.cpp
=> use MAX_JSON_TOKEN_COUNT in parsing sdp json

src/source/PeerConnection/SessionDescription.c, tst/PeerConnectionApiTest.cpp
WIP, will add test for deserializeSessionDescriptionInit as well.
=> Add test for serializeSessionDescriptionInit

src/include/com/amazonaws/kinesis/video/webrtcclient/Include.h, src/source/Signaling/Client.c, src/source/Signaling/LwsApiCalls.c, src/source/Signaling/LwsApiCalls.h, src/source/Signaling/Signaling.c, src/source/Signaling/Signaling.h, src/source/Signaling/StateMachine.c, tst/SignalingApiFunctionalityTest.cpp
=> Refreshing ICE should not require re-connection

src/source/Ice/IceAgent.c, src/source/Ice/IceAgent.h, src/source/Ice/IceUtils.c, src/source/Ice/IceUtils.h, tst/IceFunctionalityTest.cpp
move IceAgentAddIceServer to parseIceServer in iceUtils
=> move IceAgentAddIceServer to parseIceServer in iceUtils

tst/PeerConnectionFunctionalityTest.cpp, tst/SignalingApiTest.cpp, tst/WebRTCClientTestFixture.h
Add test that uses ICE_TRANSPORT_POLICY_RELAY and waits until two PeerConnections go to connected
=>     Add connectTwoPeersForcedTURN

src/source/Sdp/Serialize.c
N/A
Fix the bug. It is caught in UndefinedBehaviorSanitizor.
=> Fix serialize bug of possible index out of bound

src/source/Ice/TurnConnection.c
interlock turn connection send
=> interlock turn connection send

src/source/Dtls/Dtls.c, src/source/Include_i.h, src/source/Signaling/ChannelInfo.c
Also, fixes on the DTLS negative path on teardown
=> Channel info alignment

src/source/Ice/TurnConnection.c, src/source/Ice/TurnConnection.h, tst/TurnConnectionFunctionalityTest.cpp
remove unused param. Add more turn connection unit test
=> remove unused param. Add more turn connection unit test

src/include/com/amazonaws/kinesis/video/webrtcclient/Include.h, src/source/Dtls/Dtls.c, src/source/Dtls/Dtls.h, src/source/PeerConnection/PeerConnection.c, tst/DtlsApiTest.cpp
Add generatedCertificateBits to KvsRtcConfiguration
Resolves #102
=> Allow certificate generation bits to be configured via Public API

src/include/com/amazonaws/kinesis/video/webrtcclient/Include.h, src/source/Ice/IceAgent.c, src/source/Ice/IceAgent.h, src/source/Ice/IceAgentStateMachine.c
enable configuration ice timeouts
=> enable configuration ice timeouts

.travis.yml, src/source/Dtls/Dtls.c, src/source/PeerConnection/PeerConnection.c, src/source/PeerConnection/Rtp.c, src/source/Sctp/Sctp.c, tst/PeerConnectionFunctionalityTest.cpp, tst/RtpFunctionalityTest.cpp, tst/WebRTCClientTestFixture.cpp, tst/WebRTCClientTestFixture.h
Create two PeerConnections and wait till they exchange audio/video
=> Add PeerConnectionFunctionalityTest.exchangeMedia

.travis.yml, src/source/Ice/IceAgentStateMachine.c
=> Enable UBSAN halt_on_error

samples/kvsWebRTCClientMasterGstreamerSample.c
*Issue #, if available: KinesisVideo-5374*
- Added signal handler to capture any abort actions by the user
- On interrupting streaming, the cleanup process will be completed before application exists
=> KinesisVideo-5374-add-signal-handler-for-safe-cleanup

tst/TurnConnectionFunctionalityTest.cpp
KinesisVideo - 5340
Adding unit test for the lock added for https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/commit/75e47eb09d2ef491f962a8d04dafd5a0882cd748.
Thread sanitizer would fail if the above commit is reverted.
=> Unit test for TURN connection send data lock

README.md
*Issue #, if available: KinesisVideo-5375*
=> Add log level setting guide in README.md

src/include/com/amazonaws/kinesis/video/webrtcclient/Include.h, src/source/PeerConnection/DataChannel.c, src/source/PeerConnection/DataChannel.h, src/source/PeerConnection/PeerConnection.c, src/source/PeerConnection/PeerConnection.h, src/source/Sctp/Sctp.c, src/source/Sctp/Sctp.h, tst/DataChannelApiTest.cpp, tst/DataChannelFunctionalityTest.cpp, tst/PeerConnectionFunctionalityTest.cpp, tst/WebRTCClientTestFixture.cpp, tst/WebRTCClientTestFixture.h
=> Implement DataChannel creation

README.md
N/A
Add instruction in README about how to set AWS region through environment variable.
=> Update readme to include setting AWS region

README.md
*Issue #, if available:* 
https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/issues/110
Add IoT Instruction for how to setup IoT and sample policy and sample code.
Resolve https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/issues/110.
=> Add IoT instructions in readme

src/include/com/amazonaws/kinesis/video/webrtcclient/Include.h, src/source/Ice/IceAgent.c, src/source/Ice/TurnConnection.c, src/source/PeerConnection/PeerConnection.c, src/source/PeerConnection/Retransimitter.c, src/source/PeerConnection/Rtcp.c, src/source/Rtcp/RtcpPacket.c, tst/SignalingApiTest.cpp
Minor: adding small variation to signaling send message test
=> Fixing compoud RTCP packet handling

src/source/Ice/IceAgentStateMachine.c
=> avoid stepping state in CleanUp in IceAgentStateMachine

src/include/com/amazonaws/kinesis/video/webrtcclient/Include.h, src/source/Ice/ConnectionListener.c, src/source/Ice/IceAgent.c, src/source/Ice/IceAgent.h, src/source/Ice/IceUtils.c, src/source/Ice/Network.c, src/source/Ice/Network.h, src/source/Ice/SocketConnection.c, src/source/Ice/SocketConnection.h, src/source/Ice/TurnConnection.c, src/source/Ice/TurnConnection.h, src/source/Include_i.h, tst/IceFunctionalityTest.cpp, tst/TurnConnectionFunctionalityTest.cpp
=> use non-blocking socket.

src/include/com/amazonaws/kinesis/video/webrtcclient/Include.h, src/source/Ice/IceAgent.c, src/source/Ice/IceAgent.h, src/source/Ice/IceAgentStateMachine.c, src/source/Ice/IceAgentStateMachine.h
=> add iceAgent state waiting for remote credential

src/source/PeerConnection/JitterBuffer.c, tst/JitterBufferFunctionalityTest.cpp
https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/issues/223
There is edge case when jitter buffer rejects a packet if that packet is out of range, as the ownership of packet is expected to be on jitter buffer, it should free the packet but it didn't.
* Add unit test to verify this is happening.
* free the packet if it is not pushed into jitter buffer.
Fix https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/issues/223
=> Fix issue when jitter buffer rejecting packet caused memory leak

.travis.yml, tst/suppressions/TSAN.supp
Add suppressions to tst/suppressions/TSAN.supp
=> Enable TSAN

src/include/com/amazonaws/kinesis/video/webrtcclient/Include.h, src/source/Dtls/Dtls.c, src/source/Dtls/Dtls.h, src/source/PeerConnection/PeerConnection.c, tst/DtlsApiTest.cpp, tst/PeerConnectionFunctionalityTest.cpp
Add generatedCertificateBits to KvsRtcConfiguration if you want the old behavior still
=> Implement ECDSA Key Generation

src/source/PeerConnection/Rtcp.c
Before we only handled the original ssrc.
Resolves #232
=> Handle REMB for retransmission ssrc as well

README.md
=> update travis build status url

src/source/Ice/IceAgent.c
=> In iceAgent, do not signal fatal error if fail to send to STUN server.

README.md
=> update travis build link url

samples/Common.c, src/include/com/amazonaws/kinesis/video/webrtcclient/Include.h
=> Don't bail out on an error in re-create in samples.

samples/kvsWebRTCClientMaster.c
=> print correct status instead of STATUS_NULL_ARG

CMakeLists.txt, README.md
This is now under BUILD_DEPENDENCIES
=> Remove BUILD_OPENSSL

README.md, src/include/com/amazonaws/kinesis/video/webrtcclient/Include.h, src/source/Dtls/Dtls.c, src/source/Dtls/Dtls.h, src/source/PeerConnection/PeerConnection.c, src/source/PeerConnection/SessionDescription.c, tst/PeerConnectionApiTest.cpp, tst/PeerConnectionFunctionalityTest.cpp, tst/WebRTCClientTestFixture.cpp, tst/WebRTCClientTestFixture.h
=> Enabling pre-generated certificates for DTLS

samples/kvsWebRTCClientMasterGstreamerSample.c, tst/IceApiTest.cpp, tst/JitterBufferFunctionalityTest.cpp
Ran test with valgrind and hit multiple uninitialized value issue. Fixed two, need to fix more.
=> Fix uninitialized values found by valgrind and remove unused param

samples/kvsWebRTCClientMasterGstreamerSample.c, src/source/Signaling/LwsApiCalls.c
=> Change the OOM return value from the content store to general OOM

src/include/com/amazonaws/kinesis/video/webrtcclient/Include.h
=> Cleanup include.h file

src/source/Rtp/RtpPacket.c
Everything should be big endian
=> Fix endianness in RTP Serialization

src/source/Ice/TurnConnection.c
=> clean up turn allocation in failed state

samples/kvsWebRTCClientMaster.c, samples/kvsWebRTCClientMasterGstreamerSample.c, samples/kvsWebRTCClientViewer.c
=> Fixing a crash in samples and adding logging of the status code

samples/Common.c, src/source/Signaling/LwsApiCalls.c
Adding ability to control verbosity using env variable
=> Adding env variable parsing for logger log level

src/source/Signaling/LwsApiCalls.c, src/source/Signaling/LwsApiCalls.h, src/source/Signaling/StateMachine.c, tst/SignalingApiFunctionalityTest.cpp, tst/WebRTCClientTestFixture.h
Issue: https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/issues/311
Issue #311 
=> Proactively checking for the credentials expiration

samples/kvsWebRTCClientViewer.c
*Issue #, if available: #316*
Resolves #316 
=> [issue-316] Add missing signal handler registration in Viewer app

src/source/Signaling/LwsApiCalls.c
=> use same log level for sending signaling message as receiving

.travis.yml, src/source/Sctp/Sctp.c, src/source/Sctp/Sctp.h
=> in freeSctpSession, deregister from sctp timer first

samples/Common.c, src/include/com/amazonaws/kinesis/video/webrtcclient/Include.h, src/source/Dtls/Dtls.c, src/source/Ice/ConnectionListener.c, src/source/Ice/IceAgent.c, src/source/Ice/IceAgentStateMachine.c, src/source/Ice/IceUtils.c, src/source/Ice/Network.c, src/source/Ice/SocketConnection.c, src/source/Ice/TurnConnection.c, src/source/PeerConnection/JitterBuffer.c, src/source/PeerConnection/PeerConnection.c, src/source/PeerConnection/Retransimitter.c, src/source/PeerConnection/Rtcp.c, src/source/PeerConnection/SessionDescription.c, src/source/Rtcp/RollingBuffer.c, src/source/Rtcp/RtpRollingBuffer.c, src/source/Rtp/Codecs/RtpH264Payloader.c, src/source/Rtp/RtpPacket.c, src/source/Signaling/LwsApiCalls.c, src/source/Signaling/Signaling.c, src/source/Stun/Stun.c, tst/IceFunctionalityTest.cpp, tst/SignalingApiFunctionalityTest.cpp
=> replace CHK_LOG_ERR_NV with CHK_LOG_ERR

src/source/Ice/SocketConnection.h, src/source/Ice/TurnConnection.c, src/source/Ice/TurnConnection.h
=> add turn state timeout to TURN_STATE_CHECK_SOCKET_CONNECTION

samples/kvsWebRTCClientMasterGstreamerSample.c
=> add is-live=TRUE to audiotestsrc and videotestsrc to mimic live source

src/source/Ice/Network.c, src/source/Ice/Network.h, src/source/Ice/SocketConnection.c, src/source/Ice/SocketConnection.h, src/source/Ice/TurnConnection.c
=> configure socket to not emit SIG_PIPE

src/source/PeerConnection/SessionDescription.c, tst/SdpApiTest.cpp
i receive offer for two video tracks with the same codec 
i add two transceivers with VP8 tracks
expected answer MUST contain two different ssrc
=> two video tracks with same codec

src/source/Ice/IceAgent.c, src/source/Ice/IceAgent.h, src/source/Ice/TurnConnection.c, tst/IceFunctionalityTest.cpp, tst/PeerConnectionFunctionalityTest.cpp
=> enable using multiple turn server

samples/kvsWebRTCClientViewer.c
=> fix sigint handling for viewer sample

samples/Common.c, samples/kvsWebRTCClientViewer.c
=> add non trickle ice support for viewer

samples/Common.c
=> record start time for calculating answer generation

samples/Common.c, src/source/Ice/IceAgent.c, src/source/Ice/IceAgent.h, src/source/Ice/IceAgentStateMachine.c, src/source/Ice/IceUtils.c, src/source/Ice/IceUtils.h, src/source/Ice/Network.h, src/source/Ice/TurnConnection.c, tst/IceFunctionalityTest.cpp
=> add ability to configure TURN protocol.

src/source/Ice/IceAgent.c
=> cancel candidate gathering task when ice shuts down

src/source/Ice/TurnConnection.c, src/source/Ice/TurnConnection.h
=> cleanup turnConnection cancel timer logic.

src/source/Ice/Network.c, src/source/Include_i.h
=> enable TCP_NODELAY for tcp socket

CMake/Dependencies/libopenssl-CMakeLists.txt
=> Update openssl version

CMake/Dependencies/libgtest-CMakeLists.txt, samples/Common.c
=> Updating to the latest PIC and C Producer codebases. Fixing gtest cmake

src/source/Ice/ConnectionListener.c
=> remove duplicate CVAR_WAIT in connection listener

src/include/com/amazonaws/kinesis/video/webrtcclient/Include.h, src/source/Ice/IceAgent.c, src/source/Ice/IceAgent.h, src/source/Ice/IceAgentStateMachine.c, src/source/Ice/TurnConnection.c, src/source/PeerConnection/PeerConnection.c, src/source/PeerConnection/PeerConnection.h, tst/IceFunctionalityTest.cpp, tst/PeerConnectionFunctionalityTest.cpp
* Fix various TSAN warnings originated for ICE.
=> * Add ICE restart api.

src/source/Signaling/FileCache.c, tst/SignalingApiFunctionalityTest.cpp
=> fix bug where updating signaling cache entry fails.

src/source/Ice/IceAgent.c, src/source/Ice/SocketConnection.h
=> fix leak when ice restart fails. add EPERM to retriable socket error.

.travis.yml
Accidentally disabled these when testing CMake changes
=> Re-enable builders

samples/Common.c, samples/kvsWebRTCClientViewer.c, src/include/com/amazonaws/kinesis/video/webrtcclient/Include.h, src/source/Dtls/Dtls.c, src/source/Dtls/Dtls.h, src/source/Ice/ConnectionListener.c, src/source/Ice/IceAgent.c, src/source/Ice/IceAgent.h, src/source/PeerConnection/PeerConnection.c, src/source/PeerConnection/SessionDescription.c, tst/DataChannelApiTest.cpp, tst/DataChannelFunctionalityTest.cpp, tst/PeerConnectionFunctionalityTest.cpp, tst/SdpApiTest.cpp, tst/suppressions/TSAN.supp
=> add closePeerConnection api to trigger DTLS close.

src/source/Ice/SocketConnection.c
=> properly handle SSL_read return code in socketConnectionReadData

CMake/Dependencies/libkvsCommonLws-CMakeLists.txt, CMake/Dependencies/libkvspic-CMakeLists.txt
=> Update pic and producer C to latest

samples/Common.c, src/include/com/amazonaws/kinesis/video/webrtcclient/Include.h, src/source/PeerConnection/PeerConnection.c, tst/DataChannelFunctionalityTest.cpp
=> Add PRtcDataChannel to datachannel callback arguments

src/source/PeerConnection/PeerConnection.c, src/source/PeerConnection/PeerConnection.h
Resolves #503
With this fix, I was able to connect to Pion over data channel.
=> Allow ICE username/password up to 256 bytes

src/source/Dtls/Dtls.c
*Issue #, if available: #508*
Resolves #508
=> Fix the broken data channel

CMakeLists.txt, README.md, samples/Common.c, samples/Samples.h, samples/kvsWebRTCClientMaster.c, samples/kvsWebRTCClientMasterGstreamerSample.c, samples/kvsWebRTCClientViewer.c
- Add file logging to samples
- CMake unnecessary variables cleanup ( as pointed out in #535 )
=> Add file logging option in samples and cmake cleanUp

CMakeLists.txt, samples/discoverNatBehavior.c, src/include/com/amazonaws/kinesis/video/webrtcclient/Include.h, src/source/Ice/NatBehaviorDiscovery.c, src/source/Ice/NatBehaviorDiscovery.h, src/source/Ice/Network.c, src/source/Include_i.h, src/source/Stun/Stun.c, src/source/Stun/Stun.h
=> add utility program to detect NAT behavior

CMake/Dependencies/libkvsCommonLws-CMakeLists.txt, CMakeLists.txt
Issue: https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/issues/547
=> Fix a typo: LIBWEBSOCKET -> LIBWEBSOCKETS

README.md
=> Removing todo from ipv6 from readme

src/source/PeerConnection/Rtp.h
Matches value in libwebrtc.
https://groups.google.com/forum/#!topic/discuss-webrtc/gH5ysR3SoZI
=> Lower RTP MTU to 1200

src/source/Ice/IceAgent.c, src/source/Ice/IceAgent.h, src/source/Ice/NatBehaviorDiscovery.c, src/source/Ice/Network.c, src/source/Ice/Network.h, src/source/Ice/SocketConnection.c, src/source/Ice/SocketConnection.h, tst/IceApiTest.cpp, tst/IceFunctionalityTest.cpp, tst/TurnConnectionFunctionalityTest.cpp
=> do not do socket bind for relay canddiate sockets

CMake/Dependencies/libkvsCommonLws-CMakeLists.txt
=> Update to latest cproducer

CMakeLists.txt, src/include/com/amazonaws/kinesis/video/webrtcclient/Include.h, src/include/com/amazonaws/kinesis/video/webrtcclient/Stats.h, src/source/Include_i.h, src/source/Metrics/Metrics.c, src/source/Metrics/Metrics.h
*Issue #, if available: #578 *
- Set up basic implementations for public RTC metrics APIs. 
- Upcoming changes:
- ICE Metrics
- Filing up some of the portions of public APIs 
=> Implemented metrics public api

src/source/PeerConnection/PeerConnection.c, src/source/Sdp/Deserialize.c, src/source/Sdp/Sdp.h, src/source/Sdp/Serialize.c, tst/PeerConnectionApiTest.cpp, tst/SdpApiTest.cpp
=> Fix swapped serialization and deserialization naming

src/source/Ice/TurnConnection.c
=> free socketConnection in TURN_STATE_CLEAN_UP

src/include/com/amazonaws/kinesis/video/webrtcclient/Include.h, src/include/com/amazonaws/kinesis/video/webrtcclient/Stats.h, src/source/Ice/IceAgent.c, src/source/Ice/IceAgent.h, src/source/Metrics/Metrics.c, src/source/Metrics/Metrics.h, tst/IceApiTest.cpp, tst/MetricsApiTest.cpp
#578 
- Implementation of ICE server stats within the SDK (https://www.w3.org/TR/webrtc-stats/#ice-server-dict*)
- Added logging ability through environment variable `LOG_STATS`
- Unit test for ICE server stats pulling
=> [Issue 578] ice server stats

README.md, src/source/Ice/TurnConnection.c
=> add Debug section in README

samples/Common.c, samples/Samples.h, samples/kvsWebRTCClientMaster.c
=> Ice server and signaling stats usage example

.github/ISSUE_TEMPLATE/questions-help.md
=> Properly label questions

src/source/PeerConnection/Retransimitter.c
=> Remove the second freeRtpPacket call in cleanup

samples/kvsWebRTCClientMaster.c, src/include/com/amazonaws/kinesis/video/webrtcclient/Include.h, src/include/com/amazonaws/kinesis/video/webrtcclient/Stats.h, src/source/Metrics/Metrics.c, src/source/Metrics/Metrics.h, src/source/PeerConnection/PeerConnection.c, src/source/PeerConnection/Retransimitter.c, src/source/PeerConnection/Rtcp.c, src/source/PeerConnection/Rtp.c, src/source/PeerConnection/Rtp.h, src/source/Rtcp/RtcpPacket.h, src/source/Rtp/RtpPacket.h, tst/PeerConnectionFunctionalityTest.cpp, tst/RtcpFunctionalityTest.cpp, tst/RtpRollingBufferFunctionalityTest.cpp, tst/WebRTCClientTestFixture.cpp, tst/WebRTCClientTestFixture.h
work in progress implementing
https://www.w3.org/TR/webrtc-stats/#dom-rtcoutboundrtpstreamstats
=> Outbound stats

CMake/Dependencies/libkvsCommonLws-CMakeLists.txt
Update Producer C to match the release note, e7d4868
=> Update Producer C

samples/kvsWebRTCClientMaster.c
The sample video clock is slower than real time clock. Over time, the delay gap becomes bigger.
=> Fix backward drift clock on master sample

CMake/Dependencies/libkvsCommonLws-CMakeLists.txt
=> Updating to latest common lib commit

samples/Common.c, samples/Samples.h, samples/kvsWebRTCClientMaster.c, samples/kvsWebRTCClientMasterGstreamerSample.c
=> fix race condition in sample on sampleStreamingSessionList

samples/Common.c, samples/Samples.h, src/include/com/amazonaws/kinesis/video/webrtcclient/Stats.h, src/source/Ice/IceAgent.c, src/source/Ice/IceAgent.h, src/source/Metrics/Metrics.c, src/source/Metrics/Metrics.h, tst/MetricsApiTest.cpp
*Issue #, if available: #578 *
- Stats to pull to get information such as server source, IP address and port of the selected candidates
- Added a sample function to pull ICE candidate stats
- Also made few cleanup changes to IceServerStats
- Added unit test
=> Ice selected candidate stats

src/include/com/amazonaws/kinesis/video/webrtcclient/Include.h, src/source/PeerConnection/Rtcp.c, src/source/PeerConnection/Rtp.c
Exposes onPictureLoss callback to public api
`onPictureLoss` is called for both PLI and FIR rtcp packets
=> Transceiver onPictureLoss

src/include/com/amazonaws/kinesis/video/webrtcclient/Stats.h, src/source/Metrics/Metrics.c, src/source/Metrics/Metrics.h, src/source/PeerConnection/JitterBuffer.c, src/source/PeerConnection/JitterBuffer.h, src/source/PeerConnection/PeerConnection.c, src/source/PeerConnection/PeerConnection.h, src/source/PeerConnection/Retransimitter.c, src/source/PeerConnection/Rtcp.c, src/source/PeerConnection/Rtp.c, src/source/PeerConnection/Rtp.h, src/source/PeerConnection/SessionDescription.c, src/source/Rtp/RtpPacket.h, tst/JitterBufferFunctionalityTest.cpp, tst/MetricsApiTest.cpp, tst/PeerConnectionFunctionalityTest.cpp, tst/WebRTCClientTestFixture.h
this PR implements RTC inbound stats as defined here https://www.w3.org/TR/webrtc-stats/#dom-rtcinboundrtpstreamstats
=> inbound stats

src/source/Ice/TurnConnection.c
=> replace assert with warning when ipv6 turn peer is added.

src/source/PeerConnection/PeerConnection.c, src/source/PeerConnection/Rtcp.c
=> Change log level to DLOGS for rtcp receiver reports

src/include/com/amazonaws/kinesis/video/webrtcclient/Stats.h
Placeholder PR for RTCDataChannelStats  https://www.w3.org/TR/webrtc-stats/#dom-rtcdatachannelstats
=> RTCDataChannelStats

samples/Common.c, samples/Samples.h, samples/kvsWebRTCClientMaster.c
=> Fix bugs in sample

src/source/Ice/IceAgent.c
Resolves the following data race:
```
WARNING: ThreadSanitizer: data race (pid=19302)
Read of size 8 at 0x7fafec7a5fd0 by thread T8:
#0 incomingDataHandler /home/travis/build/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/src/source/Ice/IceAgent.c:2220:24 (libkvsWebrtcClient.so+0x1fc74)
#1 connectionListenerReceiveDataRoutine /home/travis/build/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/src/source/Ice/ConnectionListener.c:380:29 (libkvsWebrtcClient.so+0x19f3e)
Previous write of size 8 at 0x7fafec7a5fd0 by thread T16 (mutexes: write M1167, write M1182):
#0 iceAgentReadyStateSetup /home/travis/build/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/src/source/Ice/IceAgent.c:2022:45 (libkvsWebrtcClient.so+0x2af33)
#1 executeReadyIceAgentState …
```
=> Fix data race while accessing pDataSendingIceCandidatePair

src/source/PeerConnection/SessionDescription.c
=> fixes applying non-zero offset to null pointer

src/source/PeerConnection/SessionDescription.c
=> fix applying non-zero offset to null pointer part 2

.github/Doxyfile, .github/DoxygenLayout.xml, .github/Introduction.md, src/include/com/amazonaws/kinesis/video/webrtcclient/Include.h, src/include/com/amazonaws/kinesis/video/webrtcclient/NullableDefs.h, src/include/com/amazonaws/kinesis/video/webrtcclient/Stats.h
- Updated doxyfile to add callgraphs and clean up a few things
- Updated header files to abide by doxygen formatting standards
=> Doxyfile and header file updates

samples/Common.c, samples/kvsWebRTCClientViewer.c
=> Fix non trickle ice in sample

.travis.yml
=> Install graphviz on alpine docker to generate call graph

src/source/Sdp/Serialize.c
=> Fixing incorrect check for NULL in SDP serializeOrigin API

src/source/Signaling/StateMachine.c
=> Avoiding NULL deref in get token state on null credentials

samples/Common.c, src/source/Metrics/Metrics.c, src/source/PeerConnection/JitterBuffer.c, src/source/PeerConnection/PeerConnection.c
fix bug: for a 32-bit system will try to cast to 64-bit address we will overflow
[827](https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/issues/827)
=> fix bug: for a 32-bit system will try to cast to 64-bit address we will overflow

samples/Common.c, src/source/Metrics/Metrics.c, src/source/PeerConnection/JitterBuffer.c, src/source/PeerConnection/PeerConnection.c
fix bug: for a 32-bit system will try to cast to 64-bit address we will overflow
Issue #, if available:
827
Description of changes:
=> fix remaining issues on 32-bit casting to 64-bit address

src/source/Ice/IceAgent.c
#813 
Current round trip time (https://www.w3.org/TR/webrtc-stats/#dom-rtcicecandidatepairstats-currentroundtriptime) must be calculated on receiving any binding response. However, the code calculates this only when iceCandidatePair does not succeed. This PR fixes it by moving the code piece out of this block and calculating the round trip whenever a binding response on the pair is received
Resolves #813 
=> Fix round trip time calculation

samples/Common.c, samples/kvsWebRTCClientMaster.c
#906 
#905 
- Fix and minor cleanup of samples
Resolves: 
#906  
#905 
=> sample fixes

.travis.yml
=> Add new Clang compiler mbedTLS build to CI

samples/Common.c
Resolves https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/issues/935
=> Fix logical error in freeSampleConfiguration

samples/Common.c, tst/SignalingApiFunctionalityTest.cpp
=> Samples memory leak fix

CMake/Dependencies/libkvsCommonLws-CMakeLists.txt
=> Update Producer C to include SSCANF

src/source/Ice/SocketConnection.c
=> Fixing sendto call when the send is not able to send the entire chunk

README.md
=> README: fix syntax error in IAM policy

src/include/com/amazonaws/kinesis/video/webrtcclient/Include.h, src/source/PeerConnection/SessionDescription.c, src/source/Signaling/LwsApiCalls.c
=> Fixing CodeQL warnings

src/source/Ice/IceAgent.c
=> fix log message for new ice candidate protocol

CMake/Dependencies/libkvsCommonLws-CMakeLists.txt
=> Rebasing on top of the latest common lib comit

CMake/Dependencies/libkvsCommonLws-CMakeLists.txt
=> Rebasing on the latest common

samples/Common.c, samples/Samples.h, src/source/Ice/IceAgent.c
=> Removing pending queue if session creation fails

samples/Common.c
=> show in samples how to set transceiver direction

samples/Common.c
Issue #1100 
Removing the adding timer call from under the sample object lock. Also fixing an incorrect usage of atomics.
Check/Set != atomic exchange
=> Fixing deadlock in the sample

scripts/check-sample.sh
=> Fix check-sample script

src/source/PeerConnection/JitterBuffer.c, src/source/PeerConnection/JitterBuffer.h, tst/JitterBufferFunctionalityTest.cpp
=> fix bug comparing timestamp with sequence number

samples/Common.c, samples/Samples.h, samples/kvsWebRTCClientMaster.c, samples/kvsWebRTCClientMasterGstreamerSample.c, samples/kvsWebRTCClientViewer.c, scripts/generate-iot-credential.sh
no
Add the iot credential sample, and one script to generate all the stuff of iot credential provider. The script is based on the kvs tutorial and readme, and I hope this script can save the time of people try the iot credential provider at the first time.  This pr is not necessary, so it depends on you need this or not. You can drop this pr if it is not suitable here.
=> Add the iot credential sample, and one script to generate all the stuff of iot credential provider.

samples/Common.c, samples/Samples.h, samples/kvsWebRTCClientMaster.c, samples/kvsWebRTCClientMasterGstreamerSample.c, samples/kvsWebRTCClientViewer.c
* Removed prototype change and new bool.
* Moved all static declarations about useIot in samples to Samples.h
* replaced dynamic if/else with compile time if/else
=> Edit IoT Credentials Sample

src/source/Crypto/Dtls_openssl.c
Add defensive programming guard to openssl implementation of dtlsSessionPutApplicationData, similar to many other functions in this library to return error if this function is passed null arguments to prevent segfault crashes.
I ran into this issue while debugging a valgrind failure. Due to subtleties in shutdown timing, in rare cases this function would be invoked with null arguments and segfault.
=> Check null arg in openssl dtlsSessionPutApplicationData

.github/default.json, .travis.yml, CMake/Dependencies/libusrsctp-CMakeLists.txt
- Fix static build with custom seccomp profile
- Fix usrsctp build (`1ade45cbadfd19298d2c47dc538962d4425ad2dd`)
=> Enabling only alpine with custom profile

src/include/com/amazonaws/kinesis/video/webrtcclient/Include.h
Correct the ref link.
N/A
Correct document link for RtcOnIceCandidate interface.
=> Correct document link for RtcOnIceCandidate

README.md
=> Update windows readme pthreads

CMake/Dependencies/libkvsCommonLws-CMakeLists.txt
=> Update producer C release tag to v1.2.0

samples/Samples.h
=> remove unused tid.

samples/Common.c
=> fix the bug of media thread.

.github/workflows/close-stale-issues.yml
- Added github action: https://github.com/marketplace/actions/close-stale-issues
- This will enforce SLAs for auto resolution and to keep the communication going, optimizing time taken to resolve issues.
- Will improvise based on how it runs.
=> Initial stale PR template

.github/workflows/close-stale-issues.yml
Fix stale issue github action. 
=> Fix stale issue PR template

.github/workflows/close-stale-issues.yml, samples/Common.c, samples/Samples.h, samples/kvsWebRTCClientViewer.c, src/source/Sctp/Sctp.c
=> Realign branches during transition

README.md
=> Update README to include instructions for pull requests.

scripts/parse_status.py
=> Fix scripts/pare_status.py for non-status #defines (#1268)

samples/Common.c, src/source/Ice/IceAgent.c
=> typo: typo fix

CMakeLists.txt, src/source/PeerConnection/PeerConnection.c
This will log the git hash being used. Will be useful when customers attach logs and we would not have to request git hash to debug issues.
=> Log git hash

samples/kvsWebRTCClientMasterGstreamerSample.c, samples/kvsWebRTCClientViewer.c
=> Missing the public API switch in the other samples

src/source/Signaling/Signaling.c
=> Fix Fetch error retry cases

.github/ISSUE_TEMPLATE/bug_report.md, .github/ISSUE_TEMPLATE/questions-help.md, .github/workflows/close-stale-issues.yml
- Use action provided by aws-actions
- Modify the way labelling is done to ensure better automated issue handling
=> Update stale action workflow

samples/Common.c
Signed-off-by: Alex.Li [zhiqinli@amazon.com](mailto:zhiqinli@amazon.com)
#1306
#1273
#1380
#541
When we entering `freeSampleStreamingSession`, `pSampleConfiguration->sampleConfigurationObjLock` will be locked before `timerQueueCancelTimer`:
https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/blob/2dff44fea83a79336fda676ba2801d0d77417cd1/samples/Common.c#L552
If `pregenerateCertTimerCallback` was fired at this moment as well,
`pregenerateCertTimerCallback` will wait for lock `pSampleConfiguration->sampleConfigurationObjLock` forever:
https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/blob/2dff44fea83a79336fda676ba2801d0d77417cd1/samples/Common.c#L960
Which might cause dead lock and `timerQueueCancelTimer` …
=> Fix possible dead lock when `freeSampleStreamingSession`

scripts/parse_status.py
=> account for hexidecimal numbers

samples/kvsWebRTCClientMasterGstreamerSample.c
=> Invoke gst_object_unref on allocated ele ments

src/source/Signaling/FileCache.c, tst/SignalingApiFunctionalityTest.cpp
=> Fix file caching

.github/workflows/ci.yml, CMake/Dependencies/libwebsockets-CMakeLists.txt
=> Fix CI for forked branches

src/source/Ice/ConnectionListener.c
* On behalf of @Dw9 . Same as #1569 , and all merge conflicts fixed.
=> fix WSAPoll failed when set POLLPRI flag

CMakeLists.txt
* On behalf of @hassanctech. Same as #1554 but rebased to latest develop.
=> add paths for fedora

samples/kvsWebRTCClientMasterGstreamerSample.c, src/source/Ice/TurnConnection.c
* On behalf of @bkneff . Same as #1618 (which is based off of #1398) but rebased and merge conflicts resolved with latest develop.
* In their own words: "Provide an example gstreamer pipeline for Raspberry Pi hardware encoding.  Tested on Raspberry Pi 3"
=> Bkneff patch 2

src/source/Ice/IceAgent.c
* On behalf of @zhuker. Same as #1495 but rebased to latest develop.
=> wrong port/address on debug log

.github/workflows/ci.yml, .github/workflows/codecov.yml, .github/workflows/codeql-analysis.yml, .github/workflows/doxygen-gh-pages.yml
Replace pull_request_target with pull_request; update versions for actions 
=> Replace pull_request_target with pull_request

CMakeLists.txt, README.md
=> Fix build dependencies off and add version requirements in readme

samples/Common.c
#1694 
Unlock the lock in the cleanup.
=> Unlock mutex in case of error

samples/Common.c, samples/Samples.h, src/include/com/amazonaws/kinesis/video/webrtcclient/Include.h, src/include/com/amazonaws/kinesis/video/webrtcclient/Stats.h, src/source/Ice/IceAgent.c, src/source/PeerConnection/SessionDescription.c, src/source/Rtcp/RtcpPacket.h
=> IoT CertificateId as Stream Name.

src/include/com/amazonaws/kinesis/video/webrtcclient/Include.h, src/include/com/amazonaws/kinesis/video/webrtcclient/Stats.h, src/source/Ice/IceAgent.c, src/source/PeerConnection/SessionDescription.c, src/source/Rtcp/RtcpPacket.h
=> If local ICE is invalid, return from sending packet.

src/include/com/amazonaws/kinesis/video/webrtcclient/Include.h
=> Replace STUN with SCTP in a comment

.github/PULL_REQUEST_TEMPLATE.md
=> Modify the PR template

samples/kvsWebRTCClientBasicStorageSession.c, samples/kvsWebRTCClientMaster.c, samples/kvsWebRTCClientMasterGstreamerSample.c, samples/kvsWebRTCClientViewer.c, src/source/PeerConnection/PeerConnection.c
=> Do Not Send SCTP Packets when Data Channel is Disabled

samples/kvsWebrtcClientMasterGstSample.c
=> Fix comment typo regrading the default source behavior

.github/build_windows_openssl.bat, .github/workflows/ci.yml
https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/issues/1767
Added missing path to pthread, libssl, libcrypto, websockets DLLs
=> Fix Windows tests

samples/Common.c
=> sample: remove unused pIotCoreThingName

CMake/Dependencies/libkvsCommonLws-CMakeLists.txt, CMakeLists.txt, README.md, src/include/com/amazonaws/kinesis/video/webrtcclient/Include.h, src/include/com/amazonaws/kinesis/video/webrtcclient/Stats.h, src/source/Ice/IceAgent.c, src/source/PeerConnection/SessionDescription.c, src/source/Rtcp/RtcpPacket.h, src/source/Signaling/LwsApiCalls.c, src/source/Signaling/Signaling.c
- Pulling in changes from main to develop
- To ensure the 2 branches are in sync
- Using git commands, still pending CI
- Testing via CI. Main branch passes CI. 
=> Main to dev

README.md
=> Remove '$' from ReadMe command

.github/workflows/ci_fork.yml, .github/workflows/close-stale-issues.yml, .github/workflows/codeql-analysis.yml, .github/workflows/doxygen-gh-pages.yml, .github/workflows/pr-desc-lint.yml
Adding CI for forked branches
To ensure the incoming changes passes CI and runs clean before merging
Added label based approval to ensure CI runs only if approved to run
Pending testing with a forked branch
=> CI modification

src/source/Ice/TurnConnectionStateMachine.c
Issue #, if available:*
- Fromx functions of turn connection state machine
- Need to unlock the turn mutex before calling timerQueueUpdateTimer, but simply putting the unlock in that function results in hard to understand code. Moved mutex lock out of check function and placed it into fromx functions for clarity.
- Mutex locks moved around, unlock added before calling timerQueueUpdateTimer.
- Tested with CI & ThreadSanitizer
=> Move mutexes into getNextFn for turn state machine

CMakeLists.txt, src/source/Ice/IceAgent.c, src/source/Ice/IceAgent.h
- Cherry pick viewer fix from master to develop
- To sync with master branch
- Viewer fix specific commit cherry pick
- Testing with CI
- Confirmed sample works
=> Viewer fix (#1953)

README.md
Update Windows build
Missing pkg-config, fixing the language
Modified the readme
Not needed since it is only a readme update
=> [README] Update Windows instructions

.github/workflows/ci.yml, .github/workflows/pr-desc-lint.yml, src/include/com/amazonaws/kinesis/video/webrtcclient/Include.h, src/source/Ice/IceAgent.c, src/source/PeerConnection/SessionDescription.c, src/source/PeerConnection/SessionDescription.h, src/source/Sdp/Deserialize.c, tst/SdpApiTest.cpp
* This pull request includes a rebase of #1914 onto the latest develop branch. For detailed information, please refer to the linked PR. The focus of this description is on the changes made in this pull request.
* The action "PR Description Check / check-description (pull_request)" has been enhanced for robustness. Previously, the mechanism for counting the number of characters in each section (e.g., "What was changed," "Why was it changed," etc.) relied on `sed` to extract the character count between section titles and the next asterisk. However, this method proved inadequate when contributors utilized asterisks for bullet points or italics in Markdown syntax. The search query has been updated to reference the full section header name, which is unlikely to appear …
=> Reduce hash table size for SDP transceivers

CMakeLists.txt
* Bumping version for upcoming release.
* To prepare for the release.
* Modifying the version in the CMakeLists.
* CI to pass.
=> Bump project version in CMake

CMakeLists.txt
- Change the version from 1.11.1 to 1.12.0
- This release contains enough to not be considered a minor release.
- Edit the value in the CMakeLists.txt
- The CI as this change will not break anything.
=> Bump the version from 1.11.1 to 1.12.0

src/source/Crypto/Tls_mbedtls.c
- This allows devices using embedded cert to passed to mbedtls API
- In cases where, readFile is not actually fread, avoids making mbedtls use fread
=> Tls_mbedtls: Read the cert with `readFile` before parse
