src/source/Include_i.h
src/source/PeerConnection/PeerConnection.c

Use RAND_bytes instead of rand for ICE uFrag/uPwd generation

---

samples/kvsWebRTCClientMasterGstreamerSample.c

*Description of changes:* Not freeing the memory allocated to hold video app src and audio app src before.

Fix memory leak from gst sample

---

src/source/PeerConnection/SessionDescription.c
tst/PeerConnectionApiTest.cpp

```
==18070==ERROR: AddressSanitizer: stack-buffer-overflow on address 0x7ffee67b67b4 at pc 0x00010983f1cf bp 0x7ffee67b6710 sp 0x7ffee67b6708
READ of size 4 at 0x7ffee67b67b4 thread T0
#0 0x10983f1ce in deserializeRtcIceCandidateInit SessionDescription.c:648
#1 0x1094946e4 in com::amazonaws::kinesis::video::webrtcclient::PeerConnectionApiTest_deserializeRtcIceCandidateInit_Test::TestBody() PeerConnectionApiTest.cpp:24
```

Fix off-by-one in RtcIceCandidateInit parsing

---

src/source/Rtp/RtpPacket.h
tst/RtpFunctionalityTest.cpp

```
==39931==ERROR: AddressSanitizer: stack-buffer-overflow on address 0x7ffee2919e24 at pc 0x00010d6ecf6b bp 0x7ffee2919bc0 sp 0x7ffee2919bb8
READ of size 4 at 0x7ffee2919e24 thread T0
#0 0x10d6ecf6a in setRtpPacketFromBytes RtpPacket.c:138
#1 0x10d355af5 in com::amazonaws::kinesis::video::webrtcclient::RtpFunctionalityTest_packetUnderflow_Test::TestBody() RtpFunctionalityTest.cpp:40
```

Fix stack-buffer-overflow in setRtpPacketFromBytes

---

tst/SignalingApiFunctionalityTest.cpp
tst/SignalingApiTest.cpp

CI now runs integration tests, these don't pass currently

Disable tests that fail with ACCESS/SECRET key enabled

---

src/include/com/amazonaws/kinesis/video/webrtcclient/Include.h
src/source/PeerConnection/PeerConnection.c
src/source/PeerConnection/PeerConnection.h
src/source/PeerConnection/SessionDescription.c
src/source/PeerConnection/SessionDescription.h
tst/SdpApiTest.cpp

*Description of changes:* Update code logic to accept case when rtx payload type doesn't exist, it can still continue to check other codecs instead of exiting.

Handle case when Rtx payload type doesn't exist in offer/answer

---

src/source/PeerConnection/SessionDescription.c

*Description of changes:* Without rtcp-rsize, rtcp doesn't work on Chrome. Verified working on Chrome and Safari with rtcp-rsize.

Without rtcp-rsize, rtcp doesn't work on chrome

---

src/source/PeerConnection/Rtp.c
src/source/PeerConnection/SessionDescription.c
tst/SdpApiTest.cpp

*Description of changes:* In cases RTX doesn't exist in offer, we don't need to keep rolling buffer and retransmitter. 

Doesn't create rolling buffer and retransmitter if not needed

---

src/source/PeerConnection/Retransimitter.c
src/source/PeerConnection/Rtp.c
src/source/PeerConnection/Rtp.h
src/source/Rtcp/RollingBuffer.c
src/source/Rtcp/RollingBuffer.h
src/source/Rtcp/RtpRollingBuffer.c
src/source/Rtcp/RtpRollingBuffer.h
src/source/Rtp/RtpPacket.c
src/source/Rtp/RtpPacket.h
tst/RollingBufferFunctionalityTest.cpp
tst/RtpFunctionalityTest.cpp
tst/RtpRollingBufferFunctionalityTest.cpp
tst/SdpApiTest.cpp

*Description of changes:* Previous impl of RTP rolling buffer rely on the header index and tail index impl of rolling buffer. Refactor to decouple two implementations. 
1. Add last index to track which index to look at for the rtp rolling buffer.
2. Bug fix of  sequence number % MAX_UINT16 which results in sequence number lands in a range of [0..65534]. 
3. Add unit test for rtp rolling buffer and fix other tests due to refactoring.

Decouple rtp rolling buffer logic from rolling buffer

---

samples/Common.c
src/include/com/amazonaws/kinesis/video/webrtcclient/Include.h
src/source/PeerConnection/PeerConnection.c
src/source/Sctp/Sctp.c
src/source/Sctp/Sctp.h

#56 
Properly manage sctp life cycle. Now multiple peerConnection with sctp should work. And sctp is shutdown when its parent peerConnection is freed.

fix sctp lifecycle handling

---

.travis.yml
CMakeLists.txt
src/source/Dtls/Dtls.c
src/source/Ice/IceAgent.c
src/source/Sctp/Sctp.c
tst/IceApiTest.cpp
tst/IceFunctionalityTest.cpp
tst/RtcpFunctionalityTest.cpp
tst/RtpFunctionalityTest.cpp
tst/SignalingApiFunctionalityTest.cpp
tst/SignalingApiTest.cpp
tst/WebRTCClientTestFixture.cpp

Before we only built our samples/library code with warnings, this builds
the tests with them enabled as well

Enable compiler warnings when building tests

---

samples/Common.c

Print human readable error when Access/Secret keys are unset in samples

---

.travis.yml

*Issue #, if available:* 
N/A
Only override gcc4.4 and use g++ to build test and run test.

Undo g++ override, run unit test for gcc4.4 build

---

src/source/Signaling/LwsApiCalls.c
src/source/Signaling/Signaling.c
src/source/Signaling/Signaling.h

add option to compare clientPeerId when checking existing message.

add option to compare clientPeerId when checking existing message

---

src/source/Signaling/LwsApiCalls.c

When the service doesn't error out but we timeout to connect the termination doesn't trigger a termination of the service driving listener thread. This is tested by manual fault injection yet. Will be following up with automated injection test.

Terminate the listener thread on connection timeout.

---

samples/kvsWebRTCClientMaster.c

Initialization of `frame.presentationTs` is missing in `sendVideoPackets`. It is initialized in `sendAudioPackets`.

Initialize frame.presentationTs in sendVideoPackets

---

src/source/Ice/SocketConnection.c
src/source/Ice/SocketConnection.h

TURN doesn't require client certificates
Relates to: #82

Don't generate client certificate for TURN TLS

---

src/include/com/amazonaws/kinesis/video/webrtcclient/Include.h
src/source/PeerConnection/PeerConnection.c
src/source/PeerConnection/PeerConnection.h
src/source/PeerConnection/Rtp.c

Add KvsRtcConfiguration to public API that will allow users to configure
things that aren't available via WebRTC standard. Add single member for MTU.
Resolves #64

Allow MTU to be configured via public API

---

samples/kvsWebRTCClientMaster.c
samples/kvsWebRTCClientMasterGstreamerSample.c
samples/kvsWebRTCClientViewer.c

*Issue #, if available: #66 *
- The current implementation has a hard coded verbosity level `VERBOSE`
- The patch changes this level to the default log level `WARN`

Set logging level for the sample application to default log level.

---

src/source/Ice/TurnConnection.c
src/source/Ice/TurnConnection.h

*Issue #, if available:* N/A KinesisVideo-5339
*Description of changes:* 
https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/blob/master/src/source/Ice/TurnConnection.c#L567
The send data is in multi-thread but sendDataBuffer will be copied locally and send, but without the lock it is possible to overwrite the data in other thread.

Add send lock to guard sendDataBuffer

---

samples/kvsWebRTCClientMaster.c
samples/kvsWebRTCClientMasterGstreamerSample.c
samples/kvsWebRTCClientViewer.c

*Issue #, if available: #123 *
- Removed setting of log level in samples
- For more logging information, run the application by setting env variable `AWS_KVS_LOG_LEVEL`

[Issue-#123] Remove setting default log level in samples

---

README.md
samples/kvsWebRTCClientMaster.c
samples/kvsWebRTCClientMasterGstreamerSample.c
samples/kvsWebRTCClientViewer.c

…pplications
*Issue #, if available: #125 *
- Print friendly messages to indicate code flow instead of cluttering the output with logs
- Logs can still be enabled by setting the env variable
Resolves #125 

[#125] Print friendly success messages while executing sample applications

---

src/source/Signaling/LwsApiCalls.c

*Issue #, if available: KinesisVideo-5381*
- Removed mandatory hexdump of AWS and channel information while running samples
- Hexdump will now be available for log levels WARN, ERROR and FATAL

[KinesisVideo-5381] Enable LWS hexdump only for certain log levels

---

tst/CMakeLists.txt

This isn't needed anymore since we are GitHub only

Drop BP_BUILD_LIB path

---

.gitignore
.travis.yml
CMakeLists.txt
README.md
cmake-scripts/libopenssl-CMakeLists.txt
cmake-scripts/libsrtp-CMakeLists.txt

* CC/CXX is now respected across all dependencies
* OpenSSL and LibSRTP can now be configured via arguments to CMake
* Add travis build that ensures cross compiles do not regress

Update CMake to make cross-compiles easier

---

samples/kvsWebRTCClientMasterGstreamerSample.c

*Issue #, if available:  #158 *
Limiting the number of frames results in streams getting stuck. Removing the num-buffers parameter to fix this.
Resolves #158 
Limiting the number of frames to be recorded in GST pipeline leads to streams getting stuck. Removed the num-buffers argument in the samples to fix this.

Remove the argument to limit recording a fixed number of frames

---

src/source/PeerConnection/Rtcp.c
tst/RtcpFunctionalityTest.cpp

*Issue #, if available:* 
https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/issues/156
* Add test for validating if variables get initialized. 
* Add initialization to avoid crash. 
* https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/issues/45 will be the follow up for actually respect the compound packets.

Add test for receving compound rtcp packet

---

src/source/Ice/TurnConnection.c
src/source/Ice/TurnConnection.h

Issue: https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/issues/165
*Issue #165 , if available:*
Circular lock dependency leading to a dead lock. Traced most of the codepaths which seem to be OK with the exception of the callback. The cross-dependency of ICE and Turn connection are hard to break as both are low-level layers.

Deadlock fix in Turn Connection.

---

samples/Common.c
samples/Samples.h

*Issue #, if available: #51 *
- Added logic to allow detection of paths in AWS_KVS_CA_CERT environment variable.
- Logic:
1. First, a check is performed to see if the env variable is set
2. If not, CMAKE default path is checked. If Cmake detected a cert, the cert is used, else, we bail out because no cert is found
3. If env is set, a check is performed to see if it is an direct path to the file or a path which contains the file
4. If it is a direct path, a check is performed to see if it has a file extension .pem. 
5. If not, the path is searched for a file with extension .pem. 
6. If no such file is available, step 2 is performed again.
7. If the file is found, the file look up succeeds.
Resolves #51 
By submitting this pull request, I confirm that you can use, …

[Issue #51] Accept path to cert in AWS_KVS_CACERT_PATH

---

samples/Common.c
src/include/com/amazonaws/kinesis/video/webrtcclient/Include.h
src/source/Ice/IceAgent.c
src/source/Ice/IceAgentStateMachine.c
src/source/Ice/Network.c
src/source/Ice/Network.h
src/source/Ice/TurnConnection.c
src/source/Ice/TurnConnection.h
tst/TurnConnectionFunctionalityTest.cpp

*Issue #, if available: #113*
- Added provision to set callback to whitelist/blacklist specific network interfaces
- This will give the user more flexibility to choose known interfaces to scan for ICE candidate gathering
- The callback can be set by setting the setFilterFn member of RtcConfiguration to the user's custom filter function
Resolve #113 

[Issue-113] Allow interface filtering while gathering local ICE candidates

---

src/source/Stun/Stun.h

*Issue #, if available:* 
https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/issues/184
Previous check would consider data/send/binding indication as error, update to only check for error types.
Resolve https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/issues/184

Compare stun packet type with only error types

---

src/source/PeerConnection/Retransimitter.c
src/source/PeerConnection/Rtp.c
src/source/PeerConnection/SessionDescription.c
tst/SdpApiTest.cpp

If not RTX payload type is set use the same payload type as
the sender.

Support NACK without distinct PayloadTypes

---

cmake-scripts/libwebsockets-CMakeLists.txt

This branch is for active development, and is seeing API breaking changes
Resolves #211

Pin libwebsockets to v3.2.0 and not the stable branch

---

src/source/PeerConnection/PeerConnection.c

rfc5764 defines the rules as
* 127 < B < 192 -- forward to RTP
* 19 < B < 64   -- forward to DTLS
Resolves #208

Fix DTLS-SRTP Demuxing

---

src/source/PeerConnection/PeerConnection.c
src/source/PeerConnection/SessionDescription.c
tst/SdpApiTest.cpp

*Issue #, if available: #148 *
- Avoid hard coding transceivers to `SENDRECV` in `addTransceiver()`
- Currently, the SDP sets transceiver direction to sendrecv always, irrespective of the local transceiver direction. This breaks SDP exchange in Firefox. 
- If transceiver direction is unset, the SDP attribute will be set to inactive.
- The change in this patch ensures that local transceiver direction is taken into account while populating the SDP.
- This is part 1 of the 2 part change where the remote transceiver direction is taken into account to mutate the local transceiver accordingly.
Unit testing:
- Added unit tests to verify if the directions in the SDP are set accordingly. Directions tested: sendrecv, sendonly, recvonly
Resolves #148 
By submitting this …

[Issue-148] Properly create transciever direction in SDP Answer

---

samples/kvsWebRTCClientMaster.c
samples/kvsWebRTCClientMasterGstreamerSample.c
samples/kvsWebRTCClientViewer.c

*Issue #, if available: #124 *
- Replaced use of PIC Functions such as CHK_STATUS, CHK and CHK_ERROR with standard C calls from sample
- Removed used of other PiC functions wherever applicable and replaced with standard C functions.
- Removed use of DLOG functions. 
Resolves #124 

[Issue-124] Remove use of PIC from samples

---

src/source/PeerConnection/JitterBuffer.c
src/source/PeerConnection/PeerConnection.c
src/source/Rtp/RtpPacket.c

N/A
Travis reported some leaks in createRtpPacket, as the ownership was handed over to jitter buffer, it need to clean up the rtp packets.
https://travis-ci.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/jobs/296211416

Fix some potential memory leak in peer connection and jitterbuffer

---

src/source/PeerConnection/SessionDescription.c
tst/PeerConnectionApiTest.cpp

When looking for the `candidate` key we would improperly inspect values
also. If a value began with `candidate` we would assume it was a key and
would take the next value.
Instead properly iterate only through keys.
Resolves #268

Fix deserializeRtcIceCandidateInit

---

CMakeLists.txt

Global install of usrsctp and jsmn can't be found

Remove NO_DEFAULT_PATH from find_library

---

src/source/Ice/SocketConnection.c
src/source/Ice/SocketConnection.h

handle EAGAIN and EWOULDBLOCK from sendTo

---

src/source/PeerConnection/PeerConnection.h

Must be alphanumeric and '+' or '/' only
https://webrtc-review.googlesource.com/c/src/+/167281

Fix ICE ufrag/pwd generation

---

src/include/com/amazonaws/kinesis/video/webrtcclient/Include.h
src/source/PeerConnection/Rtcp.c
src/source/PeerConnection/Rtcp.h
src/source/PeerConnection/Rtp.h
src/source/Rtcp/RtcpPacket.h
tst/RtcpFunctionalityTest.cpp

handle received rtcp PLI packet

PLI: handle picture loss rtcp packet

---

src/source/Rtp/RtpPacket.c

Don't use putInt16, we don't want host aware operations.
Co-authored-by: Alex Zhukov <alex.zhukov@uber.com>

When constructing a RTP packet SeqNum must be big endian

---

src/source/PeerConnection/SessionDescription.c
tst/SdpApiTest.cpp

*Issue #, if available: #301 *
- Add h.264 fmtp / opus fmtp in the answer only if the offer contains fmtp attribute
- Add default fmtp in case of offering
- Added unit test to test both the scenarios - when fmtp is included in the offer and when it is not included in the offer
Resolves #301 

[issue-301] H264 FMTP

---

src/source/PeerConnection/PeerConnection.c

setRemoteDescription checked for NULL after dereferencing which may cause SIGSEGV

null argument check in setRemoteDescription

---

src/source/PeerConnection/PeerConnection.c

our memory sanitizer complains about the use of uninitialized memory here.

generateJSONSafeString randBuffer msan

---

src/source/Rtp/Codecs/RtpH264Payloader.c
tst/RtpFunctionalityTest.cpp

Streaming using non gstreamer master sample on raspberry pi. CPU usage reported in top before change: 12%. After change: 10%.

optimize getNextNaluLength

---

samples/Samples.h
samples/kvsWebRTCClientMasterGstreamerSample.c

Adding a command line option to select test source for GStreamer pipeline. It would be useful for testing basic sample functionality on systems with no camera attached to get the frame

Add support for test source in GStreamer sample

---

src/include/com/amazonaws/kinesis/video/webrtcclient/Include.h
src/source/Signaling/Client.c
src/source/Signaling/LwsApiCalls.c
src/source/Signaling/Signaling.c
src/source/Signaling/Signaling.h
src/source/Signaling/StateMachine.c
src/source/Signaling/StateMachine.h
tst/IceFunctionalityTest.cpp
tst/SignalingApiFunctionalityTest.cpp
tst/SignalingApiTest.cpp
tst/WebRTCClientTestFixture.cpp
tst/WebRTCClientTestFixture.h
tst/suppressions/TSAN.supp

Adding tests and fixing some of the existing tests
Issue #328 

Adding delete signaling channel API

---

src/source/PeerConnection/Rtp.c

* Issue #380 
* Description of changes:
Update raw rtp packet size to be big enough to include SRTP_AUTH_TAG_OVERHEAD

Fix incorrect rtp raw packet size

---

tst/WebRTCClientTestFixture.cpp

disable instrumented allocator due to inconsistent behavior. Sometimes it reports leak like this job: https://travis-ci.com/github/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/jobs/323627407. But re-running the job again it passes.

disable instrumented allocator

---

.travis.yml
src/source/Ice/IceAgent.c
src/source/Ice/IceUtils.c
src/source/Ice/IceUtils.h
src/source/Ice/Network.c
tst/IceApiTest.cpp
tst/IceFunctionalityTest.cpp

* Issue #115 
* Description of changes:
* Add IPv6 support for host candidates
* Refractor `iceAgentAddRemoteCandidate`
* Todo:
* Add IPv6 support for reflexive candidates
* Verify the XOR mapped address for IPv6 implementation follows STUN RFC, https://tools.ietf.org/html/rfc5389#section-15.2 (https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/issues/394)
* Add IPv6 support for TURN, https://tools.ietf.org/html/rfc6156
* Update `getIpWithHostName` to use `getaddrinfo` instead of `gethostbyname` since `gethostbyname` doesn't support IPv6 (https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/issues/395)

Add IPv6 support for host candidates

---

CMake/Utilities.cmake

Resolves #389
*Issue #389
*Description of changes: Replace CMAKE_SOURCE_DIR with CMAKE_CURRENT_SOURCE_DIR.
> By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

Switch to CMAKE_CURRENT_SOURCE_DIR

---

src/source/Ice/Network.c

*Issue #395*
*Description of changes:* Replace `gethostbyname` with `getaddrinfo`
IPv6 enabled stun server: **test-stun-dualstack-9fa4df9b63d779eb.elb.us-west-2.amazonaws.com**
Screenshot of a working example in resolving an IPv6 host:

Update getIpWithHostName to use getaddrinfo

---

src/source/Ice/IceAgent.c
src/source/Ice/IceAgent.h
src/source/Ice/TurnConnection.c
src/source/Ice/TurnConnection.h
tst/PeerConnectionFunctionalityTest.cpp

fix leaking TurnConnection obj when there are more than one turn server.

---

CMakeLists.txt

Resolves #389
Issue #389
Description of changes
In addition to the earlier PR #391 (closed) there was one more location where CMAKE_SOURCE_DIR was used.

Use CMAKE_CURRENT_SOURCE_DIR

---

src/source/Ice/IceAgent.c
src/source/Stun/Stun.c
tst/StunFunctionalityTest.cpp

*Issue #394 and #115*
* Fixed a minor bug in deserializing XOR addresses
* Verified the serialization/deserialization of XOR addresses
* Tested end-to-end with IPv6 stun server (stun:numb.viagenie.ca:3478) and observed it from chrome webrtc internal tool and tcpdump
* Added some unit tests to verify it further
* Enable gathering IPv6 reflexive candidates

Add IPv6 support for reflexive candidates

---

samples/Common.c
samples/Samples.h
samples/kvsWebRTCClientViewer.c
src/source/Signaling/Signaling.c
src/source/Signaling/Signaling.h

Issue #414 
Samples are using async get ICE config mode. The viewer application was creating the signaling client and immediately moving on to retrieving the ICE configs which returns 0. The sample assumes that there will be at least 1 turn server config avilable.
The fix is 
* In Viewer sample move the connect right after the create client before the initialization of the peer connection. This way, we will benefit from latency gains in async
* In Viewer sample, add a polling to await for the ice configs to resolve or timeuot.
* In Signaling client, in async mode to not check for known state machine states as async ICE retrieval might fail and run through other states.
By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the …

Fixing view sample with async ICE config retrieval.

---

src/source/Ice/IceAgent.c
src/source/Ice/IceAgent.h
tst/PeerConnectionFunctionalityTest.cpp

by moving ice local candidate reporting to timer thread, user can call ice api inside new local candidate callback.

move ice local candidate reporting from user thread to timer thread

---

src/source/Sdp/Serialize.c
tst/SdpApiTest.cpp

dont overwrite `pSessionDescription` memory if sdp has over `MAX_SDP_SESSION_MEDIA_COUNT` entries

handle three video tracks

---

src/include/com/amazonaws/kinesis/video/webrtcclient/Include.h
src/source/PeerConnection/PeerConnection.c

Issue #368
Description of changes:
* Introduce peerConnectionGetLocalDescription() to return pending local description.
- peerConnectionGetCurrentLocalDescription() should be for description that has already offered to the peer. There needs to be another method that can return the "pending" description. (which aligns with W3C WebRTC API)
* Fix deadlock when calling peerConnectionGetLocalDescription() from within the onIceCandidate callback.
* Fix incorrect endianness of the candidate port on the SDP.
With the above fixes, I was able to establish a peer connection in non-trickle-ice procedure.

Introduce peerConnectionGetLocalDescription() with other bug fixes

---

tst/WebRTCClientTestFixture.cpp

Enabling the instrumented allocators. As it turns out we are doing the right thing here and we don't end up with two global symbols because they are not marked as statics in their TUs.
The issues I was facing were caused by my incorrect interpretation of the readelf -Ws output from Linux with GCC. The duplicate entires were entries in .dynsym and .symtab tables which are OK and as they point to the exact same export.

Enabling instrumented allocators

---

src/include/com/amazonaws/kinesis/video/webrtcclient/Include.h
src/include/com/amazonaws/kinesis/video/webrtcclient/NullableDefs.h

RTC spec has a few attributes that have a default of NULL value/undefined. Since C does not allow us to define types such as UINTx and BOOL to a NULL value, a new data type has to be created to allow such values. 

Nullable data types

---

samples/Common.c

Use traverseDirectory from PiC so we are portable. This is part of the
Windows porting.

Update lookForSslCert to be cross-platform

---

README.md
src/source/PeerConnection/PeerConnection.c
src/source/PeerConnection/PeerConnection.h

- Added an env `DEBUG_LOG_SDP` option to get SDPs displayed
- This will useful when customers want to view the SDPs on the local machine without the need to add debug lines on their own
- Will also be useful for us to debug SDP related issues

Add SDP logging support through environment variable

---

.travis.yml
tst/CMakeLists.txt
tst/main.cpp

* Add a custom test runner to retry on failed tests
* Relax travis timeout to accommodate retries

Fix test flakiness

---

tst/WebRTCClientTestFixture.cpp
tst/WebRTCClientTestFixture.h

Make sure that we receive the ice client config by asynchronously wait for the response, similar being done in the sample. This will hopefully reduce some test flakiness.

Fix unawaited get ice server configs in test fixture

---

src/source/Dtls/Dtls.c
src/source/Dtls/Dtls.h

`X509_gmtime_adj` accepts seconds. So, the PR is a fix for the time conversion between days to seconds.

Update certificate expiration to be 1 year

---

src/source/Ice/SocketConnection.c
src/source/Ice/SocketConnection.h
src/source/Ice/Tls.c
src/source/Ice/Tls.h
src/source/Ice/TurnConnection.c
src/source/Include_i.h

The goal for this PR is to decouple Ice from OpenSSL so that we can easily swap the TLS implementation with mbedTLS (https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/issues/121).
`TlsSession` is intentionally designed to be similar to our current `DtlsSession`. The idea is that if the interfaces are similar, we can merge these 2 easily in the future, and have a single proxy class that can swap between DTLS and TLS with a single flag.

Decouple SocketConnection from OpenSSL

---

src/source/PeerConnection/JitterBuffer.c
src/source/PeerConnection/Retransimitter.c
src/source/Rtcp/RtpRollingBuffer.c
src/source/Rtp/RtpPacket.c
src/source/Rtp/RtpPacket.h
tst/RtpFunctionalityTest.cpp
tst/RtpRollingBufferFunctionalityTest.cpp

fix #518 
RtpPacket should take ownership of its pRawPacket. pRawPacket is set in the following places:
- https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/blob/master/src/source/PeerConnection/Rtp.c#L207
- rawPacket is a copy and allocated at line https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/blob/master/src/source/PeerConnection/Rtp.c#L203
- https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/blob/master/src/source/PeerConnection/Rtp.c#L216
- rawPacket is a copy and allocated at line https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/blob/master/src/source/PeerConnection/Rtp.c#L203
- https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/blob/maste …

Merge free rtp packet

---

CMakeLists.txt

Dear Developers,
here is a little enhancement that helps integrating this library with other projects. It installs resulting artifacts as long as header files.

A standard way of install build artifacts

---

src/source/Ice/Network.c
src/source/Ice/Network.h

Issue #580 
It's possible that `getaddrinfo` returns a system error, in which case we'll lose the context of what caused the error. This PR will fix this by printing out the error cause from errno.

Log errno if getaddrinfo returns EAI_SYSTEM

---

CMake/Dependencies/libkvsCommonLws-CMakeLists.txt
src/include/com/amazonaws/kinesis/video/webrtcclient/Include.h
src/include/com/amazonaws/kinesis/video/webrtcclient/Stats.h
src/source/Signaling/Client.c
src/source/Signaling/LwsApiCalls.c
src/source/Signaling/Signaling.c
src/source/Signaling/Signaling.h
tst/SignalingApiTest.cpp
tst/WebRTCClientTestFixture.cpp

This is the first cut for the signaling metrics work. Not yet finished. 
Need to
* Add EMA (Exponential Mean Averaging) for the durations once this is exposed from PIC which is ongoing
* Look for ways to not use interlocking (for performance and complexity reasons) as the metrics operations could soft-lock with reading them/updating.

Signaling metrics work

---

src/source/Sdp/Serialize.c

This is only a minor fix for line length calculation. 
Let say we have this string: "m=audio\n"
Before: lineLen = 6 (missing the last char, 'o')
After: lineLen = 7

Fix line length to include all chars

---

CMake/Dependencies/libkvsCommonLws-CMakeLists.txt
src/source/PeerConnection/SessionDescription.c
src/source/PeerConnection/SessionDescription.h
src/source/Sdp/Deserialize.c
src/source/Sdp/Sdp.h
src/source/Sdp/Serialize.c
tst/PeerConnectionApiTest.cpp
tst/SdpApiTest.cpp

Improve SDP conformation with RFC
Resolves https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/issues/587
Changes:
* SDP parser now works with CRLF and LF
* SDP line separator is now using CRLF to conform with RFC, https://tools.ietf.org/html/rfc4566#section-5
* Add unit tests for CRLF cases

Improve SDP conformation with RFC

---

src/include/com/amazonaws/kinesis/video/webrtcclient/Include.h
src/source/PeerConnection/Rtp.c

We had a forward declaration, but no implementation. Return STATUS_NOT_IMPLEMENTED
since we don't support renegotiation yet, so users shouldn't be using this.
Resolves: #604

Add definition for freeTransceiver

---

src/source/PeerConnection/Rtp.c

Accidentally introduced by c93141c1c4d9992c9190727bf5a8377ac9f1c0b1

Fix clang-format error

---

src/source/Ice/IceAgent.c

The ice candidate calculation is wrong, the spec uses `^` symbol which represents power. But, in C, this symbol means XOR.

Fix wrong ICE candidate priority calculation

---

README.md

Since our SDK is meant for low powered devices, it's very common that these devices live in a restricted network. So, it's really helpful for our customers to understand the outbound hostname and port requirements so that they can whitelist them in their network.
Note: Inbound hostname and port requirements are not important since we only use ephemeral ports.
Issue https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/issues/627

Add Outbound hostname and port requirements

---

README.md

Add missing documentation about how to set session token.
Resolves https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/issues/641

Add missing documentation about how to set session token

---

.travis.yml
CMake/Dependencies/libmbedtls-CMakeLists.txt

Fix broken mbedtls build when using old gcc.
Resolves https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/issues/651#issuecomment-663076228

Fix broken mbedtls build when using old gcc

---

src/source/PeerConnection/PeerConnection.c

https://github.com/cisco/libsrtp/blob/05563ed8e83717a5ff1e157cd3a65d399e689a35/include/srtp.h#L1289 - reference

Correcting packet size in rtcpReportsCallback() to obey srtp_protect_rtcp spec

---

samples/Common.c
src/include/com/amazonaws/kinesis/video/webrtcclient/Include.h
src/source/Metrics/Metrics.c
src/source/PeerConnection/PeerConnection.c
tst/MetricsApiTest.cpp

The public API needs to take an option mediaTrack argument (In our case PRtcRtpTransceiver) to allow pulling RTP stats for a specific transceiver. 
https://www.w3.org/TR/webrtc/#rtcpeerconnection-interface-extensions-1
To Do:
Update #615 and #634 once this is merged.

Adapt public stats interface to align with spec

---

README.md

We currently support A-law and µ-law as it's shown here, https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/blob/910a67c822a2bd9e14e3271a81cb57516add2b6e/src/source/PeerConnection/Rtp.c#L225-L229. But, the support is missing from our README.

Add G.711 PCM A-law and µ-law to README

---

src/source/PeerConnection/Rtcp.c

The RTCP packet handler creates a spew of logs which is not necessary. Changing it to verbose level to avoid the spew

Change log level to verbose to avoid spew of logs

---

CMakeLists.txt

When users want to use our SDK as a library, it's not necessary to also compile samples. So, this PR will give them an ability to not compile the samples.

Add an optional flag to not include samples

---

src/include/com/amazonaws/kinesis/video/webrtcclient/Include.h
src/include/com/amazonaws/kinesis/video/webrtcclient/Stats.h
src/source/Metrics/Metrics.c
src/source/PeerConnection/DataChannel.c
src/source/PeerConnection/DataChannel.h
src/source/PeerConnection/PeerConnection.c
tst/DataChannelFunctionalityTest.cpp
tst/suppressions/TSAN.supp

*Issue #, if available: #578 *
- Core logic of Data channel stats implemented. Data channel stats can be extracted using channel ID. Channel ID is populated in `RtcDataChannel` struct on creating a data channel and also in `onOpen()` callback.
Todo:
- Add dataChannelStats pulling to samples

Data channel stats (WIP)

---

README.md

Copy the gstreamer install command from the CPP producer SDK to ease installation of the gstreamer samples for WebRTC

Document gstreamer install in README

---

src/source/PeerConnection/PeerConnection.c
tst/SdpApiTest.cpp

N/A
It turns out that firefox sets ice-options:trickle in the leading portion of an SDP offer. This commit extends the ice-options attribute search to include the non-media portion of the SDP offer.
In the draft RFC for trickle ICE, it looks like this is allowable:
https://tools.ietf.org/html/draft-ietf-ice-trickle-21#section-3

Handle SDP offers with ice-options set as session attributes.

---

samples/kvsWebRTCClientMaster.c
src/include/com/amazonaws/kinesis/video/webrtcclient/Include.h
src/source/Metrics/Metrics.c
src/source/PeerConnection/PeerConnection.c
src/source/PeerConnection/PeerConnection.h
src/source/PeerConnection/Rtcp.c
src/source/PeerConnection/Rtp.c
src/source/PeerConnection/SessionDescription.c
tst/SdpApiTest.cpp

Fix bug with transceiver direction to correctly respond to offer according to:
https://tools.ietf.org/html/rfc3264#section-6.1
*Issue #, 468*
(1) If offer is recvonly, response should be sendonly (This fixes master sample in FF)
(2) If remote offer has only video m-line (no audio) and local (answer side) has multiple transceivers set up, the answer should still only contain 1 m-line ignoring extra local transceivers.  (This fixes master sample in Safari)
(3) Unit tests for both cases

Fix bug with transceiver direction when offer has recvonly; ensure answer is sendonly

---

samples/Common.c
samples/Samples.h
samples/kvsWebRTCClientMaster.c
src/include/com/amazonaws/kinesis/video/webrtcclient/Include.h
src/source/PeerConnection/Rtp.c

- Measures start up latency from offer to first frame for every streaming session
- Changed status code from `STATUS_SUCCESS` to `STATUS_SRTP_NOT_READY_YET` to clearly indicate packets are discarded because SRTP is not set up.

Measure start up latency from offer to first frame

---

samples/Common.c
samples/Samples.h
src/include/com/amazonaws/kinesis/video/webrtcclient/Stats.h
src/source/Ice/IceAgent.c
src/source/Ice/IceAgent.h
src/source/Metrics/Metrics.c
tst/MetricsApiTest.cpp

*Issue #, if available: #578 *
- Ice candidate pair stats (https://www.w3.org/TR/webrtc-stats/#candidatepair-dict*)
- Added usage pattern and average computation based on stats in samples.
Todo:
- Unit test to simulate values such as bytes sent, packets received, etc and validate the values returned by the public API call. This would more likely be an evolved version of a unit test. Currently, the only test for the ice candidate pair stats is Api Test.

[Issue-578] Ice candidate pair stats

---

src/source/Signaling/Signaling.c

Currently, the connect state in signaling does not respect (wait till) the time that the state machine specifies. The change is to add THREAD_SLEEP_UNTIL(time) to wait until the time that the API needs to be called.
Initially, the thought was that the connect API gets called as a direct action of the customers API call. In this case, the time would be 0 so the action will still be carried without any delay. The issue is that if the connect fails with no state transition then the next time the state machine call will be executed immediately without any delay.
There is a small chance for this tight loop to happen as on failure, we likely to transition to other states as in fromConnectState API switch case. 
NOTE: There is still a chance of hitting high TPS rate with …

Adding state machine time to call to connect state execution

---

src/source/PeerConnection/Rtcp.c

We generate a spew of logs when we do not receive a complete RTCP report, which is expected when we do not send a sender report. This PR changes log level to DLOGS to avoid the spew.

Change log level to dlogs

---

.travis.yml
check-sample.sh

Add a CI job to check samples.
Resolves https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/issues/614

Add a CI job to check samples

---

samples/Common.c
samples/Samples.h
samples/kvsWebRTCClientMaster.c
samples/kvsWebRTCClientMasterGstreamerSample.c
samples/kvsWebRTCClientViewer.c

- Organize signaling message handling by first putting them into a queue, then use a dedicated thread to process them one by one. 
- use a separate lock for media thread to access sampleStreamingSessionList to avoid media flow blocked by some potentially time consuming operations such as getIceServerConfig.

Sample refactor

---

src/source/Ice/IceAgent.c
tst/PeerConnectionFunctionalityTest.cpp

Resolves https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/issues/760
A NULL pointer dereference at `pDataSendingIceCandidatePair` can occur when the ICE agent receives data before it's finished setup. Since ICE gathering starts as soon as the user calls `setLocalDescription` and the `pDataSendingIceCandidatePair` setup is done after calling `setRemoteDescription` within the `iceAgentStartAgent`, it's possible that the ICE agent receives data in between `setLocalDescription` and `setRemoteDescription`, which will lead to a NULL pointer dereference.

Fix NULL pointer dereference

---

check-sample.sh

Currently, `check-sample` always fails when there's no AWS credentials provided. This is great and expected but we should not run the check when it's used for checking fork builds as they won't have AWS credentials in Travis.

Ignore fork builds for check-sample

---

src/include/com/amazonaws/kinesis/video/webrtcclient/Include.h
src/source/Ice/Network.c
src/source/Ice/Network.h
src/source/Ice/SocketConnection.c

Windows: fix assertion when close socket
#688 
socket() on windows do not use *nix-style file descriptors but returns a
handle to a kernel object instead, it must be closed via closesocket()

Windows: fix assertion when close socket

---

src/source/PeerConnection/Rtcp.c
src/source/PeerConnection/Rtp.c
tst/RtcpFunctionalityTest.cpp

REMB for multiple tracks
before: if transceiver was not found last known good transceiver was used
after: call `onBandwidthEstimation` for all transceivers specified in REMB packet but ONLY specified transceivers
related to but does NOT fix https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/issues/741

remb mutliple tracks

---

.travis.yml

Enable compiler warning for OSX GCC. Currently, we set it only for OSX Clang. 
Todo: 
Add compiler warning for Windows and linux as well. For Windows, the W4 flag needs to be set. 

Enable compiler warning for OSX GCC

---

CMakeLists.txt

Since libwebsockets is linked as private, the public headers are not usable. Moving libwebsockets to public fixes it on Mac. Need to verify if the fix works on other platforms through Travis.
Resolves #777 .

Fix linking error for createLwsIotCredentialProvider

---

README.md

We do not expose `createCertificateAndKey()` as a public API as mentioned in the README. This PR changes the wording around pre-gen certificate section

Fix readme for pre-gen cert section

---

samples/kvsWebRTCClientMaster.c
samples/kvsWebRTCClientMasterGstreamerSample.c
samples/kvsWebRTCClientViewer.c

Since our error codes are greater than 127, some platforms treat these codes as "success" instead. This PR fixes this issue by mapping all of our error codes to `EXIT_FAILED`.

Fix failed to propagate error codes to shell

---

samples/kvsWebRTCClientMasterGstreamerSample.c

#812 
Add check for STATUS_SRTP_NOT_READY_YET status code in gst sample to avoid log spew of writeFrame() status code.

Check for SRTP session ready in samples

---

samples/Common.c
src/source/PeerConnection/PeerConnection.c

Removing the log level setting from the peer connection. The problem is that the customers application will not be able to control the log level as the peer connection will keep resetting it every time a new one is created. Moreover, the dynamic setting of the env var will mess things up. The application should have a full control on what and when the log level should be set.
Adding extra check in the Common.c to validate the range.
Not touching the signaling - it's a longer living object. The application can control it via the ClientInfo.logLevel.

Removing log level setting from the peer connection

---

src/source/Ice/ConnectionListener.c
src/source/Ice/Network.c
src/source/Ice/Network.h
src/source/Ice/SocketConnection.c

#756 references `WSAGetLastError()`. So this pull request might relate to that issue.
These functions allow the addition of error handling support for
Windows Sockets Error Codes. On Windows the functions use `WSAGetLastError()` and
`FormatMessage()`, and on non-Windows platforms they use `errno` and
`strerror()`.
In addition, these functions provide mapping from Windows Sockets
Error Codes to BSD error codes for the error codes that are explicitly
checked in code.

Add internal getErrorCode() and getErrorString()

---

CMakeLists.txt

https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/issues/838
Changing the link ordering for kvsWebrtcSignalingClient resolves link failures when using createLwsIotCredentialProvider on Ubuntu.  I cannot verify if this breaks Windows or Mac builds.

Resolve link error when using createLwsIotCredentialProvider on Ubuntu

---

src/source/Ice/Network.c
src/source/Ice/Network.h

#756 
On Windows when calling connect() with a non-blocking socket, the
error code WSAEWOULDBLOCK is used to indicate the connection attempt
cannot be completed immediately. However the POSIX error code for this
case is EINPROGRESS.
This commit updates socketConnect() to handle both the WIN32 and POSIX
error codes mentioned above.

Handle separate error codes from connect()

---

CMakeLists.txt

In our cmake scripts, we've been using features that are only available in versions above 2.8. Users should not see weird errors as reported https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/issues/875, but instead it should bail out with the correct minimum required version.
Related Issue: https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/issues/875

Bump CMake minimum required version 2.8 -> 3.6.3

---

CMake/Dependencies/libsrtp-CMakeLists.txt

#538 
This PR generates a PC file for unix and apple platforms by running `configure`.
There is a known issue in libsrtp2.3.0 which leads to `./configure` to fail when cross compiling for ARM platforms with the error: 
```checking if OPENSSL_cleanse is broken... configure: error: in .....
configure: error: cannot run test program while cross compiling
```
SRTP Issue reference: `https://github.com/cisco/libsrtp/issues/479`
As a workaround, this PR checks if `BUILD_LIBSRTP_HOST_PLATFORM == BUILD_LIBSRTP_DESTINATION_PLATFORM` to ensure `./configure` is run only in non cross compile mode. This check can be removed once we can update libsrtp with the fix in the libsrtp repo. There is no timeline on that yet. 
We can also move to 2.2.0 but …

Generate pc file for libsrtp

---

samples/Common.c

Since the remoteCanTrickleIce is disabled for the viewer, the remote ice candidates that we retrieve from the STUN server is never sent to the other peer. From the other peer's perspective, there's no remote candidate, and, thus, no candidate was ever formed.
Related Issues:
* https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/issues/886
* https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/issues/850
* https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/issues/884

Fix unsent ice candidates in trickle mode viewer

---

src/source/PeerConnection/PeerConnection.c
tst/SdpApiTest.cpp

#890 
`ice-options` can contain multiple attribute values along with trickle. The SDK parsed the option with the assumption that `ice-options` would contain only a single value leading to performing an exact match to enable trickle ice based on the value. This PR fixes the assumption by looking for `trickle` in the list of values instead of an exact match. An unit test is also added to test this case.

Fix parsing of ice options in SDP

---

src/source/PeerConnection/Rtp.h
tst/PeerConnectionApiTest.cpp

Resolves https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/issues/894

Fix overflow RTP timestamp calculation

---

CMake/Dependencies/libbenchmark-CMakeLists.txt
CMake/Utilities.cmake
CMakeLists.txt
bench/CMakeLists.txt
bench/DtlsBenchmark.cpp
bench/WebRTCClientBenchmarkFixture.cpp
bench/WebRTCClientBenchmarkFixture.h
bench/main.cpp
src/source/Crypto/Dtls.c
src/source/Crypto/Dtls_mbedtls.c
src/source/Crypto/Tls_mbedtls.c
tst/DtlsFunctionalityTest.cpp
tst/WebRTCClientTestFixture.h
tst/suppressions/TSAN.supp

This PR replaces https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/pull/903. For some reasons, Travis doesn't want to run on that PR.
* Initiate benchmark tree
* Add Google benchmark to the dependency list
* Add USE_BENCHMARK to CMakeList
* Add Dtls benchmark
* Breaks apart application data into multiple chunks when they're bigger than the MTU in DTLS
* When given certificates are NULL, cert count is defaulted to 0
* dtlsSessionPutApplication now catches error codes
* Add Dtls functionality tests for putApplicationData and processPacket
```
Run on (8 X 2300.26 MHz CPU s)
CPU Caches:
L1 Data 32 KiB (x8)
L1 Instruction 32 KiB (x8)
L2 Unified 256 KiB (x8)
L3 Unified 46080 KiB (x1)
Load Average: 0.68, 0.48, 0.39
--------------------------------------------------------------- …
```

Add Dtls encrypt and decrypt benchmarks

---

CMake/Dependencies/libgperftools-CMakeLists.txt
CMake/Utilities.cmake
CMakeLists.txt
README.md

After linking gperftools with ENABLE_PROFILER, CPU profile can be retrieved from specifying CPUPROFILE environment variable, and heap profile can be retrieved from specifying HEAPPROFILE environment variable.

Add LINK_PROFILER CMake option to enable profiler

---

src/source/PeerConnection/Rtp.h
tst/PeerConnectionApiTest.cpp

In sending RTCP SR packets, we calculate the RTP timestamp using the relative wall clock from the first frame:
https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/blob/fddf4635e73c04044c01ed31e8b3748d355c5d5a/src/source/PeerConnection/PeerConnection.c#L602
However, this calculation becomes an error since the CONVERT_TIMESTAMP_TO_RTP doesn't have parentheses around pts and clockrate. The above calculation becomes:
Actual:
```
currentTime - pKvsRtpTransceiver->sender.firstFrameWallClockTime * clockRate / HUNDREDS_OF_NANOS_IN_A_SECOND
```
Expected:
```
(currentTime - pKvsRtpTransceiver->sender.firstFrameWallClockTime) * clockRate / HUNDREDS_OF_NANOS_IN_A_SECOND
```
Changes:
* Add unit test CONVERT_TIMESTAMP_TO_RTP with math operations
* Add parentheses in …

Fix incorrect RTP timestamp in RTCP SR

---

.gitignore
CMake/Dependencies/libmbedtls-CMakeLists.txt
CMake/Dependencies/libopenssl-CMakeLists.txt
CMake/Utilities.cmake

https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/issues/943
This change enables build parallelism in the openssl job by seeding the make command with the CMAKE_BUILD_PARALLEL_LEVEL environment variable setting, if provided.

Enable build parallelism for openssl via the CMAKE_BUILD_PARALLEL_LEVEL env variable.

---

src/source/Ice/Network.c

`IN6_IS_ADDR_UNSPECIFIED` should filter out 0000:0000:0000:0000:0000:0000:0000:0000 addresses.
Resolves https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/issues/911

Ignore unspecified local IP addresses

---

src/source/PeerConnection/PeerConnection.c

#948 
While running `export DEBUG_LOG_SDP=TRUE`, LOCAL_SDP does not get logged since we display it before creating answer/offer. This PR should fix the problem.
Resolves #948 

Fix SDP logging

---

samples/Common.c
src/include/com/amazonaws/kinesis/video/webrtcclient/Include.h
src/source/Signaling/FileCache.c
src/source/Signaling/FileCache.h
src/source/Signaling/Signaling.c
src/source/Signaling/Signaling.h
tst/SignalingApiFunctionalityTest.cpp
tst/SignalingApiTest.cpp
tst/WebRTCClientTestFixture.h

Issue #908 
Revving the version of ClientInfo struct to include the optional path to the cache file. Default value is used by specifying NULL or EMPTY_STRING. Adding test variations.
NOTE: This is an important change to allow cache file usage for many embedded devices where the partition for the binaries is locked/read-only.

Adding ability to specify the cache file path

---

samples/Samples.h

*Issue #957 *
Current Samples have UINT32 timestamps, this means that they will easily overflow in a few minutes given 10,000,000 incremented per second. When this overflow occurs, the resulting RTP frame timestamp will decrement in value, and some decoder will fail to decode RTP frames for at least a minute. By changing them to UINT64, we delay this overflow to at least a few hours.

Change Sample App timestamps to UINT64 to prevent overflow

---

CMakeLists.txt

Fix the abnormal behavior of gperftools.
I can not run this sdk with gperftools correctly, since this sdk did not add the correct link option for gcc.
The similar issue is as below. 
https://stackoverflow.com/questions/26636570/using-pprof-with-gperftools-resulting-in-curl-error

Fix gperftools

---

src/source/Ice/TurnConnection.c
tst/PeerConnectionFunctionalityTest.cpp

Resolves https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/issues/851#issuecomment-708720651
Changes:
* Add a unit test to simulate the scenario in Host/Stun and Turn
* Propagate STATUS_SOCKET_CONNECTION_CLOSED_ALREADY to the higher level

Fix TURN failed to propagate closed socket event

---

bench/DtlsBenchmark.cpp
samples/Common.c
samples/Samples.h
samples/kvsWebRTCClientMaster.c
samples/kvsWebRTCClientMasterGstreamerSample.c
src/source/Crypto/Dtls.c
src/source/Crypto/Dtls.h
src/source/Crypto/Dtls_mbedtls.c
src/source/Crypto/Dtls_openssl.c
src/source/PeerConnection/PeerConnection.c
tst/DtlsFunctionalityTest.cpp
tst/PeerConnectionFunctionalityTest.cpp

The startup latency is measured with the following procedures:
* Modified the JS example, https://awslabs.github.io/amazon-kinesis-video-streams-webrtc-sdk-js/examples/index.html,
which basically listen to "loadeddata" event which basically it lets us
know when the video starts flowing on the UI. When this event happens,
it send a data channel message to the Webrtc C SDK
* Modified the Webrtc C sample to measure the duration between connected
to the time when it receives the data channel message from the UI
In my test, I got ~9 s delay. After the fix, the delay became ~80 ms.
The issue was that we started sending frames when the connection was still
not ready. Consequently, the first I-frame was lost, and the receiver needs
to wait until the next I-frame. So, for the delay itself, it'll …

Optimize startup latency from ~9s to ~80ms

---

src/source/PeerConnection/PeerConnection.c
src/source/PeerConnection/PeerConnection.h
src/source/PeerConnection/Rtcp.c
src/source/PeerConnection/Rtcp.h
src/source/PeerConnection/Rtp.c
src/source/PeerConnection/SessionDescription.c
src/source/PeerConnection/SessionDescription.h
src/source/Rtp/RtpPacket.h
tst/RtcpFunctionalityTest.cpp
tst/RtpFunctionalityTest.cpp
tst/SdpApiTest.cpp

implements transport wide congestion control packet parsing and sending as described here https://tools.ietf.org/html/draft-holmer-rmcat-transport-wide-cc-extensions-01

transport wide congestion control

---

samples/Common.c
src/include/com/amazonaws/kinesis/video/webrtcclient/Include.h
src/source/Signaling/ChannelInfo.c
src/source/Signaling/Signaling.c
src/source/Signaling/Signaling.h
src/source/Signaling/StateMachine.c
tst/SignalingApiFunctionalityTest.cpp
tst/suppressions/TSAN.supp

* Removing async ICE functionality to avoid issues with low footprint devices and parallel execution. This also has no benefits for "master" scenario. Embedded WebRTC based viewers might incur some latency hits as for the "viewer" the ICE configuration is on the "hot" path.
* Removing periodic ICE refresh. Now, it's done on access if the ICE hasn't been retrieved or whenever the ICE credentials have expired.
* Removing timer queue from the signaling client as it's no longer needed.
* The existing state machinery is unchanged and the change is very targeted and limited.
* Extra test coverage

ICE configuration refresh functionality changes

---

src/source/Signaling/Signaling.c

Possible null access when:
1. https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/blob/b9e41d1c114acd50da3e72b05d486ebb1a0d2ff7/src/source/Signaling/Signaling.c#L132 failed, `pSignalingClient->lwsServiceLock` is invalid, goto CleanUp and call `freeSignaling`
2. https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/blob/b9e41d1c114acd50da3e72b05d486ebb1a0d2ff7/src/source/Signaling/Signaling.c#L198

Signaling: Fix possible null access in freeSignaling

---

src/include/com/amazonaws/kinesis/video/webrtcclient/Include.h

There is a small typo in src/include/com/amazonaws/kinesis/video/webrtcclient/Include.h.
Should read `registration` rather than `registeration`.
Semi-automated pull request generated by
https://github.com/timgates42/meticulous/blob/master/docs/NOTE.md

docs: fix simple typo, registeration -> registration

---

.travis.yml

- It looks like there are some issues with clang-format install on MacOS Sierra hosts that travisCI uses. Since, all we need to do is check formatting, the type of host does not matter. Linux is more stable and hence this PR moves clang-format check from OSX to Linux.

Move to linux from osx

---

samples/Common.c

It should be `remoteIceCandidateStats`.
However, `candidateType` of remote candidate is not handled in `iceAgentAddRemoteCandidate`. I will create an Issue.
https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/blob/master/src/source/Ice/IceAgent.c#L313

Fix localIceCandidateStats

---

src/include/com/amazonaws/kinesis/video/webrtcclient/Include.h
src/source/Ice/IceAgent.c

https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/issues/1031
Add the parser of ice candidate type, but need to check the turn connection object later. 

Parse ice candidate type

---

README.md

In CMakeLists:
https://github.com/codingspirit/amazon-kinesis-video-streams-webrtc-sdk-c/blob/42c249e0be61840e607c8c7666c8f8eb9f18003d/CMakeLists.txt#L30
So in readme should be `LINK_PROFILER`

README: Fix incorrect profiler option in README

---

src/source/PeerConnection/Rtp.c

Passing NULL `pFrame` to `writeFrame` might cause segfault

Check NULL for pFrame in writeFrame

---

src/source/Signaling/LwsApiCalls.c
src/source/Signaling/LwsApiCalls.h

While logging the payload that is sent from the embedded SDK, in case of sending an offer, we end up logging the credentials for the ICE Servers which is part of the OFFER payload. This PR fixes it by just logging necessary information (type of message being sent and recipient ID) to keep the information to a minimum.

Display only messsage type and recipient client ID

---

src/source/Include_i.h
src/source/PeerConnection/Rtp.c
src/source/PeerConnection/SessionDescription.c

https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/issues/1097
This PR disables TWCC until a bandwidth estimator is available and advertises REMB 

advertise REMB, disable TWCC

---

src/include/com/amazonaws/kinesis/video/webrtcclient/Include.h
src/source/PeerConnection/Rtcp.c

Since we do not support handling multiple receiver/sender reports, we do not need to log that we do not support this since it causes lot of noise.

Remove unnecessary logging

---

src/source/PeerConnection/Rtcp.c

https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/issues/1115
call sender estimation callback with twcclock unlocked to prevent potential deadlock

prevent deadlock when calling onSenderBandwidthEstimation callback

---

src/source/PeerConnection/PeerConnection.c

When disableSenderSideBandwidthEstimation is set to TRUE, it will cause Segmentation fault

Check the TWCC manager before use

---

src/source/PeerConnection/PeerConnection.c
src/source/PeerConnection/PeerConnection.h
tst/PeerConnectionApiTest.cpp

before:
`ICE_AGENT_STATE_READY` translated into `RTC_PEER_CONNECTION_STATE_NEW` if dtls is not connected  
now:
`ICE_AGENT_STATE_READY`  -> `RTC_PEER_CONNECTION_STATE_CONNECTING` if dtls is not connected   
both before and now:
`RTC_PEER_CONNECTION_STATE_CONNECTED` if dtls is connected

set correct peer connection state

---

scripts/parse_status.py
src/include/com/amazonaws/kinesis/video/webrtcclient/Include.h

#737, #1127
Two changes to improve the usability of status codes:
Add a doxygen documentation block explaining the basic concept of status codes and how they are used.
Add a utility script which will parse the main include file and print out a list of status codes with their hex value,
to make it easier for developers to debug the hex value they receive or code gen a function to convert a status code to a string.
For example:
```
$ cat src/include/com/amazonaws/kinesis/video/webrtcclient/Include.h | ./scripts/parse_status.py
STATUS_WEBRTC_BASE 0x55000000 …
```

Add script and documentation to work with status codes

---

src/include/com/amazonaws/kinesis/video/webrtcclient/Include.h

#1139 
No-op documentation change to fix various doxygen formatting issues discovered when browsing [the generated doxygen](https://awslabs.github.io/amazon-kinesis-video-streams-webrtc-sdk-c/). Specifically:
* Fixing the alignment of comments for struct members, so they appear in the generated docs along with the correct member (some were appearing for the wrong struct member
* Seperate `\addtogroup` blocks from the following object it is documenting. This was preventing certain structs/functions, such as `createPeerConnection`, from having generated docs

Fix various doxygen formatting issues

---

src/source/PeerConnection/PeerConnection.c
src/source/Rtcp/RtpRollingBuffer.c
src/source/Rtp/RtpPacket.c

createRtpPacketFromBytes() now only moves ownership of the rawPacket
argument to the PRtpPacket object if the call to
createRtpPacketFromBytes() is successful. This allows the caller to
free rawPacket in a CleanUp section without having to check if
a call to createRtpPacketFromBytes() was the source of failure.
This commit also fixes two potential double frees in
sendPacketToRtpReceiver().
This first potential double free is that the call to
createRtpPacketFromBytes() in sendPacketToRtpReceiver() succeeds, but
then the call to jitterBufferPush() fails. When this happens, then
SAFE_MEMFREE() frees pPayload. However, the subsequent call to
freeRtpPacket() then also calls free on pPayload since
createRtpPacketFromBytes() transferred ownership of pPayload to …

Update createRtpPacketFromBytes(), fix double free

---

src/source/Ice/Network.c

Indicate which option was attempted in debug logs when setting setsockopt() in 2 more places, as it is in the other usage of 
setsockopt.
This allows users to see what socket options may be unavailable on their network.

Add more detail to setsockopt logs

---

src/source/Ice/ConnectionListener.c
src/source/Ice/Network.h
src/source/Ice/SocketConnection.c
src/source/Ice/SocketConnection.h

Use `poll` system call instead of `select`.
Select fails when socket fd value is larger than 1024. This happens when running as part of a process which has already opened a lot of descriptors.
This is caused by a design bug in glibc `select` implementation.
```
BUGS
POSIX allows an implementation to define an upper limit, advertised via the constant FD_SETSIZE, on the  range  of  file  de‐
scriptors that can be specified in a file descriptor set.  The Linux kernel imposes no fixed limit, but the glibc implementa‐
tion makes fd_set a fixed-size type, with FD_SETSIZE defined as 1024, and the  FD_*()  macros  operating  according  to  that
limit.  To monitor file descriptors greater than 1023, use poll(2) instead.
```
By submitting this pull request, I confirm that …

use poll instead of select

---

src/source/PeerConnection/Retransmitter.c
src/source/PeerConnection/Rtcp.c

Adds packets resent via NACK mechanism to twcc manager.
Previously the packets were not accounted for which caused bandwidth estimator to be overly optimistic.

account for NACK resent packets in twcc

---

CMake/Dependencies/libwebsockets-CMakeLists.txt
src/source/Signaling/Signaling.c

Signed-off-by: zhiqinli@amazon.com <zhiqinli@amazon.com>
#1147 
In libwebsockets v3.2.3, there is a memory access violation issue when use mbedtls with certificates, @ycyang1229 managed to fix this via:
https://github.com/warmcat/libwebsockets/pull/2304
this PR has been merged into libwebsockets main and v4.2-stable branch. Without this patch, using mbedtls with iot certificates will always failed.
Similar to #1152 , this changes will update libwebsockets to v4.2-stable. This update will fix #1147, and replace old `ws_ping_pong_interval` with new `lws_retry_bo_t ` to manage ping behaviors, which was introduced since libwebsockets v4.+.
ref: https://libwebsockets.org/git/libwebsockets/tree/READMEs/README.lws_retry.md
By submitting this …

libwebsockets: update libwebsockets to v4.2-stable

---

samples/Common.c
samples/Samples.h
samples/kvsWebRTCClientViewer.c

Create a data channel sample
* Create a data channel from the viewer's side
* Communicate over the data channel by sending and receiving 
messages using `onopen` and `onnmessage` callbacks from master and viewer

create data channel sample

---

samples/Common.c

In the samples, the `mediaSenderThread` flag is set to false after the audio and video threads join the main thread. However, we do not cancel the thread at cleanup leading to potential lingering threads. This PR fixes a potential clean up issue that could arise increasing the number of zombie threads in the system.

Cancel the thread once mediaThreadStarted flag is set to false

---

.travis.yml
src/source/Ice/IceAgent.c
src/source/Ice/IceAgent.h

Issue #, if available:
#1174
Description of changes:
Previously, we never recorded remote candidate IP address. However, the SDP of remote candidate comprises of the protocol information. Since we did not record this information, all remote candidates being discovered would log protocol as N/A or UNKNOWN. This PR fixes this bug by storing the protocol for remote candidates.
Additionally, we also modify the logic for local candidate protocol logging by relying on pSocketConnection instead of pTurnConnection to log for all types of candidates. Although our SDK supports only UDP, it is important it is logged regardless based on SDP.
Resolves: #1174

Log ice candidate protocol appropriately

---

src/source/Ice/IceAgent.c
src/source/Ice/IceUtils.h
src/source/Rtcp/RtpRollingBuffer.c
tst/MetricsApiTest.cpp

*Issue #1255 #1256 , if available:*
Set protocol/relayProtocol of RtcIceCandidateStats following the [specification](https://www.w3.org/TR/webrtc-stats/#icecandidate-dict*).

set protocol value following the spec

---

src/source/Ice/IceAgent.c

*Issue #1249 , if available:*
When assembling sdp, candidates with new or invalid status shouldn't be serialized.

filter out invalid candidate in sdp

---

CMake/Dependencies/libwebsockets-CMakeLists.txt
CMake/Dependencies/libwebsockets-leak-pipe-fix.patch

#1263 
This change will add a patch from libwebsockets to fix pipe fd leak issue when build libwebsockets with `DLWS_HAVE_EVENTFD=0`.

libwebsockets: add patch to fix pipe fd leak issue

---

samples/Common.c
samples/kvsWebRTCClientMaster.c
src/source/Ice/ConnectionListener.c

This change addresses the following issues:
https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/issues/1237
https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/issues/1266

fix some bugs

---

samples/Common.c

We initialized locked to `TRUE` this results in an edge case bug where if the `pSampleConfiguration` is `NULL` we will try to unlocked.  Though we set the attribute for the mutex to `PTHREAD_MUTEX_RECURSIVE` which means the unlock will return an error I don't think we actually log that error anywhere.  This fixes that initial value for the `locked` boolean.

fix edge case try to unlock a mutex which is not locked in the case sample configuration is NULL

---

src/source/Signaling/LwsApiCalls.c

For example before if the request signature was too old we should just swallow that error and manifest as a timeout 0x0000000f in the sync call.  Now we have logging to indicate what the error is, for example:
```
2021-10-29 14:50:08 WARN    lwsHttpCallbackRoutine(): Received client http read response:  {"message":"Signature expired: 20211029T144008Z is now earlier than 20211029T144508Z (20211029T145008Z - 5 min.)"}
```
In this instance I tried to submit the API call 10 minutes after the time was set in the request header.

log response, particularly in case of failure

---

src/include/com/amazonaws/kinesis/video/webrtcclient/Include.h
src/source/Signaling/LwsApiCalls.c
src/source/Signaling/Signaling.c
src/source/Signaling/Signaling.h
src/source/Signaling/StateMachine.c
src/source/Signaling/StateMachine.h

There are calls to `stepSignalingStateMachine` from `executeStateFn` and `getNextStateFn` functions for a lot of states in the signaling state machine. `stepSignalingStateMachine` calls `stepStateMachine` which also contains calls to `executeStateFn` and `getNextStateFn` functions. This causes recursion and could cause the stack to overflow.
- the `stepSignalingStateMachine` is replaced with `signalingStateMachineIterator`
- calls to the `stepSignalingStateMachine` from _Signaling.c_ and _LwsApiCalls.c_ have been replaced with calls to `signalingStateMachineIterator` with their respective final states
- the `stepUntil` and `continueOnReady` attributes have been removed from the signaling client since they are no longer needed to break out …

Signaling state machine rework

---

samples/Common.c
samples/kvsWebRTCClientMaster.c
src/include/com/amazonaws/kinesis/video/webrtcclient/Include.h
src/include/com/amazonaws/kinesis/video/webrtcclient/Stats.h
src/source/Signaling/Client.c
src/source/Signaling/Signaling.c
src/source/Signaling/Signaling.h
src/source/Signaling/StateMachine.c
tst/SignalingApiFunctionalityTest.cpp
tst/WebRTCClientTestFixture.h

Add retry count metric for signaling state machine

Add Retry count retrieval in hook

---

src/source/Signaling/StateMachine.c

Currently, if number of retries is set to 1, we retry only once. However, the count indicates retry count to be 1 more than actual value which is an incorrect indication. This PR fixes it by getting retry count only after executeRetry is executed. 
In the first attempt, if call fails, retry count = 0 followed by `executeRetryStrategy` which indicates a retry. The next time the hook function is executed, the retry count would appropriately reflect the count value.

Fix retry count to indicate count only after a retry has occured

---

src/source/PeerConnection/PeerConnection.c
src/source/PeerConnection/Rtcp.c
tst/SdpApiTest.cpp

https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/issues/1331
- add a stream track in case it is null for recvonly to prevent seg fault

handle null stream track in case of recvonly

---

README.md
samples/Samples.h
samples/kvsWebRTCClientViewer.c
src/source/Signaling/LwsApiCalls.c

Merge master into develop

---

src/source/PeerConnection/SessionDescription.c
tst/SdpApiTest.cpp

https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/issues/1224
Modified the logic for populating SDP attributes in a local session description to use remote session description SDP attributes if present. 
Added a test which uses an offer with SDP attributes "BUNDLE audio video data" and checks if the answer responds with the same in its SDP attributes

added implementation and a test to use remote sdp to construct local sdp

---

.github/build_windows.bat
.github/workflows/ci.yml
.travis.yml
src/source/Signaling/Client.c

All builds working on GitHub Actions except the static build and the builds that are allowed to fail (Windows, MSAN)

GitHub actions setup

---

src/source/Crypto/Dtls_openssl.c

`SSL_free()` and `SSL_CTX_free()` calls are swapped within their respective checks.

Fix swapped SSL_free() and SSL_CTX_free()

---

.github/workflows/ci.yml
.travis.yml
CMake/Dependencies/libopenssl-CMakeLists.txt

Setup static build with tests on MacOS
Setup static build only on Linux alpine

GitHub actions setup static build

---

src/source/Signaling/LwsApiCalls.c

ResourceEndpoint length check mistakenly uses ChannelName max length.

Fix ResourceEndpoint length check

---

src/source/PeerConnection/JitterBuffer.c
tst/JitterBufferFunctionalityTest.cpp

https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/issues/1437

Addressing error handling concerns for an edge case

---

samples/Common.c

In current code, `getIceCandidatePairStatsCallback` will not be triggered if user is running viewer sample because `startStats` is not set:
```
if (startStats &&
STATUS_FAILED(retStatus = timerQueueAddTimer(pSampleConfiguration->timerQueueHandle, SAMPLE_STATS_DURATION, SAMPLE_STATS_DURATION,
getIceCandidatePairStatsCallback, (UINT64) pSampleConfiguration,
&pSampleConfiguration->iceCandidatePairStatsTimerId))) {
DLOGW("Failed to add getIceCandidatePairStatsCallback to add to timer queue (code 0x%08x). "
"Cannot pull ice candidate pair metrics periodically",
retStatus);
```
This commit will set `startStats` when received offer when sample work as viewer, which allows viewer sample gathering …

metrics: allow viewer sample to get ice candidate pair stats

---

src/source/PeerConnection/DataChannel.c

#1438 
Default should be ordered mode: https://developer.mozilla.org/en-US/docs/Web/API/RTCDataChannel/ordered
Resolves #1438 .

Fix default data channel ordering mode

---

samples/kvsWebRTCClientMasterGstreamerSample.c

https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/issues/1105
change gstreamer pipeline param framerate to 25/1.
Because the SAMPLE_VIDEO_FRAME_DURATION used for accumulate the videoTimestamp is calculated from assume video fps is 25, which definition can be find in Samples.h, so update the video framerate to 25/1.
The framerate of video
```c
// kvsWebRTCClientMasterGstreamerSample.c
gst_parse_launch("autovideosrc ! queue ! videoconvert ! video/x-raw,width=1280,height=720,framerate=[30/1,10000000/333333] ! "
```
The definition of SAMPLE_VIDEO_FRAME_DURATION 
```h 
#define DEFAULT_FPS_VALUE                        25
#define SAMPLE_VIDEO_FRAME_DURATION (HUNDREDS_OF_NANOS_IN_A_SECOND / DEFAULT_FPS_VALUE)
```
The …

fix video delay 4s

---

CMake/Dependencies/libsrtp-CMakeLists.txt
CMake/Dependencies/libusrsctp-CMakeLists.txt
CMake/Utilities.cmake
CMakeLists.txt

1. fix mips compile error when use toolchain mips-gcc472-glibc216-64bit
2. option ADD_MUCLIBC effect to all dependencies

fix mips compile error

---

samples/Common.c

*Issue #1560*
avoid deadlock via MUTEX_TRYLOCK and just try again later via timer

Fix deadlock getIceCandidatePairStatsCallback

---

.github/workflows/ci.yml
CMake/Dependencies/libbenchmark-CMakeLists.txt
CMake/Dependencies/libgperftools-CMakeLists.txt
CMake/Dependencies/libgtest-CMakeLists.txt
CMake/Dependencies/libjsmn-CMakeLists.txt
CMake/Dependencies/libjsmn-add-cmakelists.patch
CMake/Dependencies/libkvsCommonLws-CMakeLists.txt
CMake/Dependencies/libmbedtls-CMakeLists.txt
CMake/Dependencies/libopenssl-CMakeLists.txt
CMake/Dependencies/libsrtp-CMakeLists.txt
CMake/Dependencies/libusrsctp-CMakeLists.txt
CMake/Dependencies/libwebsockets-CMakeLists.txt
bench/CMakeLists.txt
samples/kvsWebRTCClientMasterGstreamerSample.c
src/CMakeLists.txt
src/source/PeerConnection/PeerConnection.h
src/source/Signaling/LwsApiCalls.c
src/source/Signaling/StateMachine.c
tst/CMakeLists.txt
tst/SdpApiTest.cpp

Firefox:
Cannot set ICE candidate for level=0 mid=audio0: No such transceiver.
Chrome:
[2023-02-01T16:48:33.986Z] [ERROR] OperationError: Failed to execute 'addIceCandidate' on 'RTCPeerConnection': Error processing ICE candidate

Fix ice candidate issue with GStreamer sample

---

src/source/Ice/TurnConnection.c

#1544 
* Add a comment clarifying that the missing `break` statement/fallthrough for the `TURN_STATE_CHECK_SOCKET_CONNECTION` case in [turnConnectionHandleStun](https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/blob/b820e2ea3d28c670da2fbc789face742cb949ef1/src/source/Ice/TurnConnection.c#L926) is intended.

Add clarifying comment for fallthrough

---

samples/Common.c
samples/Samples.h
samples/kvsWebRTCClientMaster.c
src/source/Ice/IceAgent.c
src/source/Ice/IceAgentStateMachine.c
src/source/Ice/TurnConnection.c

* Rebasing to latest develop, resolving all merge conflicts. This combines the following PRs by @jdelapla:
* https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/pull/1452 
* https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/pull/1469
* https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/pull/1472

thread cancel memory leak, recreate signaling client & lws_context whenever a significant error has occurred, verbose and debug logging for ice & turn

---

CMake/Dependencies/libkvsCommonLws-CMakeLists.txt
CMake/Dependencies/libopenssl-CMakeLists.txt
samples/Common.c

Update openssl version

---

src/source/Ice/IceUtils.c

#1614 
In the transactionIdStoreInsert function, when a new transactionId is inserted.If 'pTransactionIdStore->nextTransactionIdIndex == pTransactionIdStore->earliestTransactionIdIndex' the first transactionId will be eliminated, then the transactionIdCount should remain unchanged.

fix(project): fix issue--1614

---

CMakeLists.txt
src/source/PeerConnection/PeerConnection.c

https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/pull/1362

Mark datachannel specific code explicitly

---

configs/config_mbedtls.h
src/include/com/amazonaws/kinesis/video/webrtcclient/Include.h
src/source/Ice/IceAgent.c
src/source/Ice/TurnConnection.c
src/source/Ice/TurnConnection.h

https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/pull/1536
https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/pull/1540

Fix turn allocation taken long time when credential is incorrect

---

.gitignore
src/include/com/amazonaws/kinesis/video/webrtcclient/Include.h
src/source/PeerConnection/JitterBuffer.c
src/source/PeerConnection/JitterBuffer.h
src/source/PeerConnection/PeerConnection.c
tst/JitterBufferFunctionalityTest.cpp

1. Added tracking of tail timestamp of the buffer
2. Added overflow state tracking for when tail or head wrap around the MAX_UINT16 or MAX_UINT32 for the respective bit counts
3. Added considerations for timestamp overflow & underflow

Jitter buffer overflows

---

src/include/com/amazonaws/kinesis/video/webrtcclient/Include.h
src/include/com/amazonaws/kinesis/video/webrtcclient/Stats.h
src/source/Ice/IceAgent.c
src/source/PeerConnection/SessionDescription.c
src/source/Rtcp/RtcpPacket.h

the port is in network endian, so need to get system endian by getInt16, and then printf to log

Fix port printf in log

---

src/include/com/amazonaws/kinesis/video/webrtcclient/Include.h
src/include/com/amazonaws/kinesis/video/webrtcclient/Stats.h
src/source/Ice/IceAgent.c
src/source/Ice/TurnConnection.c
src/source/PeerConnection/SessionDescription.c
src/source/Rtcp/RtcpPacket.h

turn state change from TURN_STATE_CREATE_PERMISSION to TURN_STATE_BIND_CHANNEL always use 2s+, As a result, when only using turn to establish an ice connection, more than 2s will be used.
```
log(1).txt:1970-01-01 00:02:15 DEBUG   turnConnectionStepState(): TurnConnection state changed from TURN_STATE_ALLOCATION to TURN_STATE_CREATE_PERMISSION
log(1).txt:1970-01-01 00:02:17 DEBUG   turnConnectionStepState(): TurnConnection state changed from TURN_STATE_CREATE_PERMISSION to TURN_STATE_BIND_CHANNEL
log(1).txt:1970-01-01 00:02:17 DEBUG   turnConnectionStepState(): TurnConnection state changed from TURN_STATE_BIND_CHANNEL to TURN_STATE_READY
log(1).txt:1970-01-01 00:02:31 DEBUG   turnConnectionStepState(): TurnConnection state changed from TURN_STATE_ALLOCATION to …
```

fix turn permission delay 2s

---

README.md

Instruction to build on MacOS M1

---

CMakeLists.txt
src/source/Signaling/ChannelInfo.c
src/source/Signaling/ChannelInfo.h
tst/SignalingApiTest.cpp

What was changed?
-  By default, the user agent string for the WebRTC SDK was set to`AWS-SDK-KVS/...`. Set a WebRTC SDK specific default user agent.
Why was it changed?
- When trying to debug a problem that requires checking backend, it is impossible to understand the source of the request since this SDK depends on producer SDK. This change helps with the differentiation and simplify debugging
How was it changed?
- Setting the default format to: `AWS-WEBRTC-KVS-AGENT/<version>`
- Changed the CMake to set project version which is read to set the user agent string. This would have to be changed before every release
Testing:
- Added unit test to test out default agent string and supplied agent string
- Tested locally with samples
By …

[BUG] Set a default user agent if not provided

---

src/include/com/amazonaws/kinesis/video/webrtcclient/Include.h
src/source/Ice/Network.c
src/source/Ice/Network.h
tst/DataChannelFunctionalityTest.cpp
tst/NetworkApiTest.cpp

What was changed?
The function to extract IP address from hostname through DNS resolution is modified to parse IP address from hostname if possible and fallback on getaddrinfo() if the hostname format does not comply to format. Also added a unit test to test this under different inputs.
Why was it changed?
getaddrinfo has been noticed to take a long time to resolve or even be unreliable in smaller embedded devices. Having this in place helps in bypassing this call altogether if the IP address complies with AWS public IPv4 DNS format.
How was it changed?
Checks and parser logic is added to ensure we verify if parsing is a feasibility.
Testing:
- Local testing with samples through logs monitoring
- Testing via newly added unit tests
By submitting this pull request, I confirm that you can …

Parse IP address if the hostname conforms to Public ipv4 DNS format

---

CMake/Dependencies/libkvsCommonLws-CMakeLists.txt
README.md
samples/Common.c
samples/Samples.h
src/include/com/amazonaws/kinesis/video/webrtcclient/Include.h
src/source/Signaling/LwsApiCalls.c
src/source/Signaling/Signaling.c
src/source/Signaling/Signaling.h

Adding threadpool that is now supported from PIC. The threadpool is a part of the SignalingClient and is used to manage the threads handling Signaling Messages. 

Include and use threadpool for signaling channel messages

---

tst/TurnConnectionFunctionalityTest.cpp

Fixing a broken unit test. No functional changes.

Fix refresh permission test by checking more regularly

---

CMake/Dependencies/libkvsCommonLws-CMakeLists.txt
CMakeLists.txt
README.md

- Modified readme to include details on the new log level
- Modified readme to clarify link to release notes which advertizes the new feature
- Update CMake file to point to producer C release commit
- Updated version string to be set to 1.8.0
- To add more clarity to the available readme
- To use release producer C version
- Update related cmake files and readme details.
- N/A since the changes are not code changes.

Release branch update and readme update

---

src/include/com/amazonaws/kinesis/video/webrtcclient/Include.h
src/include/com/amazonaws/kinesis/video/webrtcclient/Stats.h
src/source/Ice/IceAgent.c
src/source/PeerConnection/SessionDescription.c
src/source/Rtcp/RtcpPacket.h

always appears 0x40100001 error when process STUN_PACKET_TYPE_BINDING_RESPONSE_SUCCESS packets
```
[W][0330 21:11:18.687][IceAgent.c:2480](MIRTC) Unable to fetch request Timestamp from the hash table. No update to totalRoundTripTime (error code: 0x40100001), stunBindingRequest
[E][0330 21:11:18.687][IceAgent.c:2603](MIRTC) operation returned status code: 0x40100001
[E][0330 21:11:18.688][IceAgent.c:2343](MIRTC) operation returned status code: 0x40100001
```
because all transactionId in binding request send from srflx candidate are the same.
See details in iceAgentSendSrflxCandidateRequest(line:1369)
update transactionId for SrflxCandidateRequest
By submitting this pull request, I confirm that you can use, modify, copy, and redistribute …

update transactionId for SrflxCandidateRequest

---

samples/kvsWebRTCClientViewer.c

*Issue #, if available:* #1801
*What was changed?* Fix log headers of kvsWebRTCClientViewer.c from [KVS Master] to [KVS Viewer]
*Why was it changed?* It is confusing.

Fix wrong log headers

---

src/source/Sctp/Sctp.c

Description of changes:
https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/issues/1782

Change usrsctp initialization function to not open raw sockets #1782

---

CMake/Dependencies/libkvsCommonLws-CMakeLists.txt
CMakeLists.txt
README.md
samples/Samples.h
src/source/Signaling/LwsApiCalls.c
src/source/Signaling/Signaling.c
src/source/Signaling/Signaling.h
tst/SignalingApiFunctionalityTest.cpp
tst/SignalingApiTest.cpp
tst/WebRTCClientTestFixture.h
tst/suppressions/TSAN.supp

https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/issues/1803
Additionally, previously the `KVS_SIGNALING_THREADPOOL` was not enabled due to the `#define` being in a different file. This fix makes sure that the threadpool is enabled and disabled correctly. This also fixes all the tests by adding missing initializations for min and max number of threads.
A new CMake flag `ENABLE_KVS_THREADPOOL` is available to configure this feature from the CMake
We do not have a way to configure this feature from CMake as correctly pointed out by the customer in the issue
Created a new CMake flag `ENABLE_KVS_THREADPOOL` and passed it to use in the SDK with `add_definitions`
*What testing was done …

Create a CMake flag to enable KVS Threadpool

---

samples/kvsWebRTCClientViewer.c
src/include/com/amazonaws/kinesis/video/webrtcclient/Include.h
src/source/Ice/IceUtils.c
src/source/PeerConnection/PeerConnection.c
src/source/PeerConnection/SessionDescription.c
src/source/Stun/Stun.c
tst/SdpApiTest.cpp

Viewer will now add trickle ice to the session level of the SDP.
Changed the SDPinit struct to include this flag, and changed the viewer sample to set it.
In cases where a media was not specified (data channel only) trickle ice was not being sent.
Added a check for canTrickle flag in peerconncetion when setting the session description. This flag is set when creating the offer by checking the SDPInit struct.
Added an SDPApi test that checks this value.

Add a=ice-options:trickle to session level of SDP as viewer

---

.github/workflows/ci.yml
samples/kvsWebRTCClientMaster.c
samples/kvsWebRTCClientViewer.c
samples/kvsWebrtcClientMasterGstSample.c
src/include/com/amazonaws/kinesis/video/webrtcclient/Include.h
src/source/Crypto/Dtls.h
src/source/Crypto/Dtls_mbedtls.c
src/source/Crypto/Dtls_openssl.c
src/source/PeerConnection/PeerConnection.c
src/source/Sctp/Sctp.c
tst/DtlsApiTest.cpp
tst/DtlsFunctionalityTest.cpp
tst/PeerConnectionApiTest.cpp

- The PR focusses on improving DTLS handshake time by moving to a state transition based approach to be more responsive to the incoming DTLS handshake messages instead of waiting 200 milliseconds to respond. (based on the timer implementation)
- DTLS over Openssl inherently takes some time based on the cryptographic suite chosen. The PR focusses on improving the existing DTLS handshake design to reduce latency from the SDK end so that the true latency is from the actual handshake process. We use the threadpool to perform the DTLS handshake and the optimization can be enabled by enabling THREADPOOL usage for the WebRTC SDK.
- Start DTLS handshake on the threadpool based on the `ENABLE_KVS_THREADPOOL` …

Dtls handshake process optimization

---

src/source/Ice/IceAgent.c

Fix the loop for ICE server parsing time to run only for the number of ICE servers checked instead of total allowable
To ensure we do not unnecessarily loop over non existent indices
Change in the loop count variable
Verified the correct value is reported when looping through the ICE servers.

Change ice server count value

---

.github/workflows/ci.yml
src/source/Crypto/Dtls_openssl.c

Added better handling of the status codes returned by the timeout functions in DTLS.
To ensure we handle all the return codes appropriately
Modified the logic in the handshake thread to respond to return values on `DTLSv1_get_timeout` and `DTLSv1_handle_timeout`
CI run and ran the master and viewer samples with JS test page as a sanity check

Dtls err handling

---

src/source/PeerConnection/PeerConnection.c

Rebased led to start time not being recorded for STUN DNS resolution
There was a metric added to record STUN DNS resolution time taken in an earlier PR and due to a faulty rebase, the start time was not recorded leadnig to large timestamp values being recorded as the time taken.
Recording start time before getaddrinfo
Local testing to confirm a valid value is printed.

Fix regression in value

---

README.md

Included instructions in the README to set up DLOGS
To ensure customers are aware of the existence of `DLOGS` log level and include instructions on how to set it up.
Added instructions in the README
Local testing by setting the log level to VERBOSE and adding the definition.

DLOGS readme update

---

samples/kvsWebRTCClientMaster.c
samples/kvsWebrtcClientMasterGstSample.c

For the master sample, these changes will reset the frame file index back to the first index when the SRTP connection is not ready to ensure the first frame sent is a key frame. The master GStreamer sample has the addition of a log line to indicate that frames were dropped. Also, using a logger was added to the GStreamer sample to replace printf() calls.
The frame file index for the master sample is incremented for every writeFrame() call, even for writeFrame() attempts before the SRTP connection is ready. Such frames are dropped, but the index is still incremented, resulting in non keyframes being sent as the first successful frames. Logging replaced printf() calls to be more versatile and consistent with the rest of our …

Fix frame indexing in master sample to handle SRTP connection not ready yet

---

samples/Common.c
samples/kvsWebRTCClientMaster.c
samples/kvsWebRTCClientViewer.c
samples/kvsWebrtcClientMasterGstSample.c
scripts/check-sample.sh

The way the sample grabs credentials from the environment. Also, using the macro "GETENV" instead of "getenv".
When I use non-temporary credentials, but have the session token env var set to empty (like this), the sample exits.
```
export AWS_ACCESS_KEY_ID=xxxx
export AWS_SECRET_ACCESS_KEY=xxxx
export AWS_SESSION_TOKEN=
```
The error code we received is 0x00000002 | STATUS_INVALID_ARG | An invalid value was specified for an argument.
Instead of passing in an empty string as the session token argument for `createStaticCredentialProvider`, pass in NULL instead.
Manually tried the sample with an empty session token and it works.
Previously:
```
export …
```

Sample: Ignore empty session token

---

samples/Common.c

Adding a missing null check before checking anything related to the string
If that check is missing and the env var is not set, the sample segfaults
It was changed by adding a null check before checking anything related to the string
Tested locally that even if the value is not, the sample does not segfault

Add missing NULL check for session token

---

samples/Common.c

Opening for #1880 to let CI run. 
Fixing compilation error when `IOT_CORE_ENABLE_CREDENTIALS` enabled.
To ensure the build runs clean. The issue does not persist in past releases and is only localized to 1.9.0. We do not want to modify the channel name that is being set in the command line option in our samples. If certificate Id is required, users can modify the sample to fit their use case.
It was fixed by removing the usage of `pIotCoreCertificateId`. 
Tested locally and confirmed media shows up on JS test page by generating a new thing following the instructions here:
https://docs.aws.amazon.com/kinesisvideostreams/latest/dg/how-iot.html#
By submitting this …

Remove pIotCoreCertificateId usage from samples.

---

tst/PeerConnectionFunctionalityTest.cpp
tst/WebRTCClientTestFixture.cpp
tst/WebRTCClientTestFixture.h

Thread detach in the tests were changed to be joinable, joined, and then the callback removed at the end of the function connectTwoPeers and similar operations throughout the test.
CI was experiencing TSAN failures.
Explained in "what was changed"
CI was used to confirm the changes fixed the issue

No more detaching threads in tests

---

src/source/PeerConnection/PeerConnection.c

#1899 
- Fixed the calculation of packets discarded in inbound rtp stats.
- We want to add up the number of packets discarded every time we receive an inbound packet to ensure the application gets the total value. 
- Changed from `pTransceiver->inboundStats.received.packetsDiscarded = packetsDiscarded;` to `pTransceiver->inboundStats.received.packetsDiscarded += packetsDiscarded;`
- Sample run to confirm no breaking change. 
- CI
Closes #1899 

Fix packetsDiscarded tracking operation

---

src/source/Signaling/Signaling.c
src/source/Signaling/Signaling.h

- Removed threadpool create in signaling since the common threadpool is used
- To ensure code is clean of unused functions
- Simple delete of the code portions with SIGNALING specific threadpool
- Ensured clean build
- Ran sample
- Allow unit test to pass

Remove tp unused

---

.github/workflows/ci.yml
src/include/com/amazonaws/kinesis/video/webrtcclient/Include.h
src/source/Ice/IceAgent.c
src/source/PeerConnection/SessionDescription.c
src/source/PeerConnection/SessionDescription.h
src/source/Sdp/Deserialize.c
tst/SdpApiTest.cpp

- Reduce the size of the following hash tables:
1. `pSeenTransceivers`: This is populated with only codecs supported by the SDK. It was originally set to allow 10000 entries leading to a hash table size of 480 KB. However, the size should be adapted to max codecs supported by SDK since the table will not have duplicate entries. With this PR, the size is set to MAX(Max_codecs_supported, min_hashtable_count), where, min_hashtable_count is 16.
2. `pUnknownCodecPayloadTypesTable`: This is populated with the first unknown codec encountered in the m section of the SDP. It was originally set to allow 10000 entries leading to a hash table size of 480KB.  However, the maximum entries in the hash table is equal to the maximum m lines the SDK supports …

Reduce hash table size for SDP transceivers

---

.github/workflows/ci.yml
scripts/verify_lib.sh

- Include cross compile builds for mbedtls. The toolchains being tested with are:
- `aarch64-linux-gnu-gcc`
- `arm-linux-gnueabi-gcc`
- Also added a script that would verify the library built matches the expected platform type and linkage
- MBedTLS cross compile build was missing.
-  Added 4 new builds - ARM64 dynamic mbedtls, ARM64 static mbedtls, ARM32 dynamic MBedTLS, ARM32 static mbedtls
- Created a new shell script that would run as part of these CI jobs to verify library file type
Sample CI output for ARM32 shared library build:
- Ran the build locally on an Ubuntu x86 EC2 instance using the `aarch64-linux-gnu-gcc` toolchain. SCPed the generated libraries …

Mbedtls cross compile in CI

---

README.md

None.
A word in the ReadMe from the sentence: This is only build if pkg-config finds GStreamer is installed on your system.
To correct the spelling/grammar of the sentence: This is only build if pkg-config finds GStreamer is installed on your system.
By replacing "build" with "built"
Reading it a few times.

Fix ReadMe Typo: build -> built

---

src/source/PeerConnection/PeerConnection.c
src/source/PeerConnection/PeerConnection.h
src/source/PeerConnection/SessionDescription.c

- Fixed the code where the SDK allocates remoteDescription member along with peer connection object, causing it to live in memory for the duration of the peer connection
- The SDP object takes up 800KB of memory to store a remote/local description. This leads to unnecessary memory usage, when the remote description is not required to remain in memory once the answer is generated. In the future, say the SDK resends the answer suspecting the viewer did not receive it, the SDK would not regenerate the answer, but would resend the same answer. A reconstruction would not be required and is not expected. 
- Switched the peer connection member from : `SessionDescription remoteSessionDescription;` to …

Ensure remote description does not live in memory for viewer duration

---

README.md
samples/Common.c
samples/kvsWebRTCClientMaster.c
src/include/com/amazonaws/kinesis/video/webrtcclient/Include.h
src/source/Crypto/Dtls_mbedtls.c
src/source/Crypto/Tls_mbedtls.c
src/source/PeerConnection/PeerConnection.c
src/source/PeerConnection/PeerConnection.h
src/source/PeerConnection/Rtp.c
src/source/PeerConnection/Rtp.h
src/source/PeerConnection/SessionDescription.c
tst/DtlsFunctionalityTest.cpp
tst/PeerConnectionApiTest.cpp
tst/RtcpFunctionalityTest.cpp
tst/RtpFunctionalityTest.cpp
tst/SdpApiTest.cpp

- Reduced default size of rolling buffer to about half of original to reduce default memory allocation
- Added new members to allow configuring rolling buffer size per transceiver
- Updated readme about usage details
- Our SDK was allocating rolling buffer worth 5 seconds of media at bitrate of 10Mbps which increases the rolling buffer size which is very large. Ideally, the bitrate depends on the media track and the codec being used. Audio tracks typically have lower bitrates than video and within audio/video, different codecs have different typical bitrates. Given this, the values should be configurable. By controlling the capacity, the SDK essentially controls the number of RTP packets the buffer holds references to. …

Rb size config

---

README.md

None
Changes some of the ReadMe's in-line code formatting to code-block formatting to provide a quick-copy button. Specified the language for the code block.
This makes following the ReadMe's instructions slightly easier as now all the commands can be copied with the click of a button. Specifying the language provides syntax highlighting to the code block.
Added two more "`" characters to the ones around the relevant commands and moved the command to a new line separate from the "```". The code language was added just after the beginning "```" in each case.
Viewing the formatted ReadMe and confirming that the quick-copy button is there and that commands are …

Add copy code buttons to github clone commands

---

.github/workflows/ci.yml
CMake/Dependencies/libkvsCommonLws-CMakeLists.txt
CMakeLists.txt
samples/CMakeLists.txt
src/source/Signaling/FileCache.c

Modified the Windows CI and deserialization logic in Signaling caching
Signaling cache was broken on Windows. This change would fix it and some tests that were disabled on Windows
By modifying the readFile in the PIC layer and fixing the deserialize function on Windows by introducing an additional check
The tests pass in the CI. Ran the sample application to make sure the cache is being used instead of the describe call

Fix signaling cache and GStreamer sample build on Windows

---

CMakeLists.txt
README.md
samples/discoverNatBehavior.c

Use a KVS STUN host instead of `stun:stun.sipgate.net:3478`
Using a KVS STUN host will help customers use discoverNatBehavior to understand their network and its interaction with KVS STUN better
Modified the string for the host name to use a KVS STUN from PDX
STUN
```
niyatim@88665a374cf5 build % ./samples/discoverNatBehavior
Usage: ./discoverNatBehavior -i network-interface-name -s stun-hostname
Using stun host: stun:stun.kinesisvideo.us-west-2.amazonaws.com:443, local network interface (null).
2024-02-08 13:29:18.091 INFO    getIpWithHostName(): ICE SERVER Hostname received: stun.kinesisvideo.us-west-2.amazonaws.com
2024-02-08 13:29:18.093 WARN …
```

Use KVS stun host in discoverNatBehavior

---

src/source/Ice/Network.c

- Add check to filter out gathering interfaces that are inactive or loopback on windows.
- This was done to ensure the SDK does not spend cycles on gathering interfaces unnecessarily and it could lead to time improvement if the getAddress operation is slow on Windows.
- Added a check to check for interfaces activity and loopback.
- Tested the sample to confirm original functionality does not break.

Filter out non-operational and loopback interfaces

---

CONTRIBUTING.md

No issues to link. Resolve conflicting information.
Change the contributions target branch from master to develop.
In the main readme, it says develop branch. Here, it says master branch. Resolve conflicting information.
Change the branch name in Contributing.md to develop from master.
Double-check the edited section for spelling mistakes.

Contributions target branch

---

samples/CMakeLists.txt

- Moving the pkg-config file search if only GST is found for windows.
- Without this change, windows customers would be mandated to install gstreamer which is not right.
- Moved the block to within the `if(GST_FOUND)` block
- CI runs to confirm everything works as expected.

Move gst blk inside GST_FOUND

---

README.md
samples/Common.c
samples/Samples.h
src/include/com/amazonaws/kinesis/video/webrtcclient/Include.h
src/include/com/amazonaws/kinesis/video/webrtcclient/Stats.h
src/source/Ice/IceAgent.c
src/source/Ice/IceAgent.h
src/source/Metrics/Metrics.c
src/source/PeerConnection/PeerConnection.c
tst/MetricsApiTest.cpp

- Switched to dynamic allocation for all ICE diagnostic members in `IceAgent` and added a new flag to allow it to be enabled through `kvsRtcConfiguration`. Disabled by default.
- Modified sizes of string members in some of these structs to reduce allocation size.
- To save memory. ICE diagnostics need not be a mandatory requirement, but must be made configurable to allow opt-in.
- Added new field in `KvsRtcConfiguration` -> `enableIceStats`
- Switched to dynamic members in `IceAgent` struct.
- Set the flag to default.
Memory consumption before this change was at 4.05MB. Also, the sizes of the structs before this change:
```
Size of ICE agent: 167184 bytes
Size of ICE candidate pair: 264 bytes
``` …

Ice memory reduction - enable ice stats flag

---

.github/workflows/ci.yml
CMakeLists.txt
src/source/Ice/IceAgent.c
src/source/Ice/IceAgent.h

- Added new flags to monitor relay candidate gathering. 
- In case of viewer connection, the getIceServerConfig resolves after candidate gathering callback exits due to which relay candidates do not get added to the list, causing the gathering callback to assume that all candidates in the local candidate list are addressed and reported. This causes connections requiring TURN to fail. Adding new checks to ensure we stop gathering callback only if candidate pair is nominated or the relay candidates are added to the list fixes this problem. Forcing TURN does not catch this issue because the timer callback waits for the local candidate list to have some entry.
- Added a flag for 2 cases: 
1. …

Viewer fix

---

samples/kvsWebRTCClientMasterGstSample.c

N/A
Added videoscale and videorate to gstreamer pipelines in samples.
we're using autovideosrc for device streams, and the detected video source is not guaranteed to be able to support 1280/720 or 25/1 fps.
Added videoscale and videorate to the gstreamer pieplines in samples
Manual testing as samples still lack automated tested.

Add videoscale and videorate

---

.github/workflows/codecov.yml

- Excluding samples from codecov to show the actual coverage
- To ensure codecov tool reports the right coverage %. By excluding samples from the calculation, the coverage value increases from 80% to 89%. Having unit tests for samples is not typical and this change can be reversed if we include any in the future.
- Changed the CI script to build with `-DBUILD_SAMPLE=OFF`.
- Confirmed by opening the codecov link to verify samples are not included in the calculation.

Remove sample from codecov

---

.github/workflows/ci.yml
README.md
samples/Common.c
samples/GstAudioVideoReceiver.c
samples/kvsWebRTCClientMasterGstSample.c

- Removed the receiver from the GstMaster sample
- PTS fix
- EOS fix
It was removed because it segfaults with the JS viewer because the JS viewer modifies caps mid-streaming. It is not supported by matroskamux in GStreamer. It has been broken but didn't manifest itself earlier because autovideosink in the previous pipeline did not work at all
Removing the receiver from the GStreamer sample application as it was non-functional
- Ran the GstSample with JS viewer and not seeing a segfault
- Ran the GstSample master with GstSample viewer and made sure the audio and video played properly
By submitting this pull request, I confirm that you can use, modify, copy, and …

[Bug] GStreamer sample

---

.github/workflows/ci.yml
.github/workflows/codecov.yml
CMake/Dependencies/libkvsCommonLws-CMakeLists.txt
CMakeLists.txt

- Fixed static building issue of SDK with mbedtls encountered on Ubuntu and added a CI for the same.
- Without this change, it seems the `libkvsCommonLws` library generated was a shared one despite setting static flag. This caused failure (complaining about compiling a shared version of libmbedtls) when trying to link mbedtls static library to shared `libkvsCommonLws` causing build failure, which surfaced this discrepancy. Same issue is not encountered with openssl, however, if static flag is set, we should make sure producer C is built static too.
- Passing in `BUILD_STATIC_LIBS` setting to producer C.
- Added a new build only CI to build mbedtls static on ubuntu.
*What testing was done for the …

Static build prodc

---

src/source/Signaling/Client.c

Issue #, if available:
What was changed?
remove redundant `retStatus` in some logs.
Why was it changed?
`retStatus` takes the position of `signalingClientCreationWaitTime`, which leads to errors when print other variables.
How was it changed?
remove `retStatus`
What testing was done for the changes?
```
before:
05-15 11:05:59.759 678 754 I 00000/SignalingClient: signalingClientFetchSync(): Attempting to back off for [0.000000] milliseconds before creating signaling client again. Signaling client creation retry count [2147483648]
after
05-15 14:09:08.539 1707 1749 I 00000/SignalingClient: signalingClientFetchSync(): Attempting to back off for [15804.994141] milliseconds before creating signaling client again. Signaling client creation retry count [7]
```
By submitting this pull request, I …

Fix log disorder in createSignalingClientSync and signalingClientFetchSync

---

src/source/Rtcp/RtcpPacket.h

Updated the MID_NTP macro definition to use the parameter passed to it.
The macro definition was not using the parameter passed to it. It was working so far because the variable name used in the macro definition happened to be same as the one at the call site.
Updated the macro definition to use the parameter passed.
The change is pretty small and does not warrant any testing. 

Fix MID_NTP macro definition

---

CMakeLists.txt
samples/CMakeLists.txt

- Adding threadpool to ensure it is installed along with other webrtc libraries
- Removing the unnecessary linkage to stun, rtp and sdp libraries in samples since we do not directly use its APIs
- Threadpool was added to ensure custom path install works for threadpool and does not cause linkage failure.
- Check the cmake file changes made in the PR
- Allowing CI to run to ensure this does not break anything
- Ran local build by setting OPEN_SRC_INSTALL_PREFIX and CMAKE_INSTALL_PREFIX paths.

Build fixes

---

.github/workflows/ci.yml
CMakeLists.txt
src/source/Ice/TurnConnection.c
src/source/PeerConnection/Rtcp.c
src/source/Sctp/Sctp.c
src/source/Signaling/LwsApiCalls.c
src/source/Stun/Stun.c
tst/JitterBufferFunctionalityTest.cpp

- Updated GHA runner to macos-12 since macos-11 is going to be deprecated ([The macos-11 label has been deprecated and will no longer be available after 28 June 2024.)](https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners/about-github-hosted-runners)
- The jobs do not start with macos-11 runner anymore.
- Changed the label on CI files
- Fixed all unused variable errors reported by mac CI.
- CI being run to test out the change.

Fix CI - unused vars

---

.github/workflows/pr-desc-lint.yml
src/source/PeerConnection/SessionDescription.c

https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/issues/2025
In the case viewer does not support a codec the master supports on 32 bit issues a bug was fixed which could cause a garbage value to be set in the sdp answer for the rtpmap attribute.
Customer reported issue, results in incorrect/buggy behavior
The `hashTableGet` fills in a UINT64 so it is expecting 8 bytes, a char* was being cast to this, but a pointer on a 32 bit system is only 4 bytes wide. This was resolved by creating an intermediate 64 bit int to hold the value then cast it back down.
Will request customer to test and confirm.  If I can get my hands on a 32 bit system I will …

fix bug 32 bit system reading 8 bytes for pointer results in overwriting 4 bytes of payloadType when writing rtpMapValue

---

src/source/PeerConnection/SessionDescription.c

https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/issues/2029
A single line was removed which re assigns a value to payloadType in the case of h265 codec.
There was asymmetric behavior in the code where for h265 we would set the payloadType twice which is confusing for the reader, all other codecs we do not do that.
The extra line of code which assigned it for a second time was removed.
Unit tests / CI.  No additional tests were added since no functional behavior was changed.

remove line which sets payloadType after it was already set

---

src/source/PeerConnection/SessionDescription.c
tst/SdpApiTest.cpp

*Issue #, if available:* https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/issues/2007
We were previously failing to increment index in an array which held the strings for rtcp-fb sdp attribute which contained `pli` and `pli nack`.  This means the line which contains `pli nack` overwrite the line which contained `pli`, but this is not the expected behavior.
It was brought to our attention via a GitHub issue referenced at the top.
There is an existing pattern where after copying over an attribute we increment the attribute number.  This was mistakenly missed, and it looks like that bug was copy/paste from the H264 section to the H265 section so it was corrected there as well.
*What testing was done for the …

fix nack pli overwrite bug

---

CMakeLists.txt

The project version number in the CMakeLists.txt file was updated from 1.8.1 to 1.9.1.
The previous version number (1.8.1) was incorrect and outdated, and it needed to be updated to reflect the current version of the KinesisVideoWebRTCClient project.
The version number was changed by modifying the project command in the CMakeLists.txt file. The line:
```
project(KinesisVideoWebRTCClient VERSION 1.8.1 LANGUAGES C)
```
was replaced with:
```
project(KinesisVideoWebRTCClient VERSION 1.9.1 LANGUAGES C)
```
No specific testing was done for this change, as it is a version number update and does not directly affect the functionality of the project.
By submitting …

Update project version from 1.8.1 to 1.9.1

---

samples/CMakeLists.txt
samples/Samples.h

N/A
Add a CMake flag that defines the pre-processor macro: `IOT_CORE_ENABLE_CREDENTIALS`. This flag is used in the samples to enable IoT credentials. Otherwise, static credentials (AK, SK, (ST)) are used.
* Makes it easier to build.
* If "-DIOT_CORE_ENABLE_CREDENTIALS=ON" cmake flag is present, it will add the pre-processor macro: `IOT_CORE_ENABLE_CREDENTIALS`. Also add a log line to indicate that it chose this path. To maintain backwards compatibility, this flag is OFF by default.
1. `cmake ..`, run kvsWebrtcClientMaster
- IoT credentials are not used.
2. `cmake .. -DIOT_CORE_ENABLE_CREDENTIALS=OFF`, run kvsWebrtcClientMaster
- IoT credentials still not used. …

Add cmake flag for iot creds

---

README.md

The readme was changed to include better instructions.
Because the information was missing from the readme.
The instructions were added to the readme.
I followed the instructions on my Mac and on an Ubuntu instance.

Add instructions for using IoT credentials in the samples and document additional cmake options

---

.github/workflows/ci.yml
.github/workflows/codecov.yml
.github/workflows/codeql-analysis.yml
.github/workflows/doxygen-gh-pages.yml
.github/workflows/pr-desc-lint.yml
.github/workflows/version-check.yml
CONTRIBUTING.md
README.md

* GitHub Actions CI configuration files
* README
* Contributing guide
* Because `master` branch is deprecated.
* The branch target in the GitHub Actions CI configuration files were changed from `master` to `main`.
* The CI check for the version bump branch target was also changed from `master` to `main`.
* Links in the README were changed to target the `main` branch.
* Contributing guide references to `master` branch were changed to `main` branch.
* Double check the spelling of the branch name.

Change branch target from master to main

---

.github/workflows/ci.yml
samples/Common.c

N/A
- GitHub actions CI. Run the master and viewer samples both with `valgrind `to check for memory leaks. Instead of kill with signal 9, it interrupts the process (signal 2) and also checks for graceful exit.
- Reduce the number of times I need to manually run this check. Automating this check will also give confidence to future developers that their change did not introduce a memory leak.
- Script overview:
- Disable logs by setting log level to 7 (silent).
- Run the master and viewer samples in the background with valgrind. The valgrind output is captured into two different files, one for each.
- After 30 seconds, interrupt the viewer (disconnect)
- After 30 more seconds, interrupt the master.
- …

Add job to run the sample and check for memory leak

---

samples/Common.c
src/source/PeerConnection/PeerConnection.c
src/source/PeerConnection/PeerConnection.h
src/source/PeerConnection/Rtcp.c
src/source/PeerConnection/Rtcp.h
src/source/PeerConnection/SessionDescription.h
tst/RtcpFunctionalityTest.cpp

* Original PR: #1934
(aside from the original's PR changes)
* Removed the IceAgentStats-related change.
* IceAgentStats changes have been handled in a separate PR..
* Removed the relevant line.
* Allowing for CI to pass.

Memory Optimization - Refactor TWCC (#1934)

---

src/include/com/amazonaws/kinesis/video/webrtcclient/Include.h
src/include/com/amazonaws/kinesis/video/webrtcclient/Stats.h
src/source/Ice/IceAgent.h

* Brought it string member length changes from the https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/pull/1947 memory optimization PR.
* Further reduced the length of some members.
* To reduce excess memory allocated through `char[length]`.
* Copying the relevant changes from the above PR and adding additional improvements.
* Allowing for CI to pass.

Shorten Stats String Lengths

---

src/source/PeerConnection/SessionDescription.c
tst/SdpApiTest.cpp

Original PR:
* #2035
(in addition to original PR changes)
* Removed the duplication of the `nack pli` attribute for h.264.
* Added the `rtcp-fb` attribute name for h.265.
* Added the following to the unit tests:
* `nack pli` and `nack` attribute lines used to validate SDP now end with an `SDP_LINE_SEPARATOR` ("\r\n") to consider that one of the lines might be a substring of another.
* Validate that both the `nack pli` and `nack` lines are present in the SDP. Previously, the test passed if one of them was missing.
To correct the above issues and properly test that `nack pli` and `nack` feedback attributes are set in the SDP.
By making the appropriate SDP changes and accounting for missed cases in the …

SDP Attribute Fixes

---

.github/workflows/ci.yml

- Actually use the GCC compiler for Mac-GCC jobs.
- Factor out the Mac jobs to use the matrix strategy for more maintainable code
- MacOS-12 runner is deprecated and blocking the other PR from getting merged: https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/pull/2089
- CI file was modified to include the changes above.
- Note that the GCC+Mac+Unit Tests combination was skipped. The GCC job previously used Clang 14. Now that it actually correctly uses GCC-14, AWS CRT CPP does not support this combination of GCC on Apple Silicon Macs: https://github.com/awslabs/aws-crt-cpp/issues/605. Note that a different compile error for AWS SDK CRT occurs for GCC on the Intel Macs too:
``` …
```

Upgrade to macos-13 and 15, use DRY for Mac jobs

---

samples/Common.c
samples/Samples.h
samples/kvsWebRTCClientMaster.c

-N/A
- Rolling buffer configuration for audio and video streams in the sample Master WebRTC client application was updated to better fit the pre-canned sample frames.
- This uses the new optional configuration API introduced in #2077.
- Reduce the memory usage of the sample application. The default rolling buffers are too big, causing extra RTP packets to get stored for the retransmitter (nacks) that the other peer would have considered too old to get retransmitted.
- Reduced the bitrate in the rolling buffer parameter for the sample frames.
- Added calls to configure transceiver rolling buffers with the new parameters, for audio and video separately.
- Ran the …

Samples: Fit the RTP transceiver rolling buffers to fit the set of sample frames

---

src/include/com/amazonaws/kinesis/video/webrtcclient/Include.h

Added the PUBLIC_API attribute to the new `configureTransceiverRollingBuffer` API.
To show `configureTransceiverRollingBuffer` as a public API in library documentation.
By adding `PUBLIC_API` before the `configureTransceiverRollingBuffer` declaration in the webrtcclient include header file.
Allowing for the CI to pass.

Specify `configureTransceiverRollingBuffer` as a Public API

---

.github/workflows/ci.yml
.github/workflows/pr-desc-lint.yml
CMake/Dependencies/libkvsCommonLws-CMakeLists.txt
CMakeLists.txt
README.md
samples/Common.c
samples/Samples.h
samples/kvsWebRTCClientMaster.c
src/include/com/amazonaws/kinesis/video/webrtcclient/Include.h
src/include/com/amazonaws/kinesis/video/webrtcclient/Stats.h
src/source/Crypto/Dtls_mbedtls.c
src/source/Crypto/Tls_mbedtls.c
src/source/Ice/IceAgent.c
src/source/Ice/IceAgent.h
src/source/Metrics/Metrics.c
src/source/PeerConnection/PeerConnection.c
src/source/PeerConnection/PeerConnection.h
src/source/PeerConnection/Rtcp.c
src/source/PeerConnection/Rtcp.h
src/source/PeerConnection/Rtp.c
src/source/PeerConnection/Rtp.h
src/source/PeerConnection/SessionDescription.c
src/source/PeerConnection/SessionDescription.h
src/source/Sdp/Deserialize.c
tst/DtlsFunctionalityTest.cpp
tst/MetricsApiTest.cpp
tst/RtcpFunctionalityTest.cpp
tst/RtpFunctionalityTest.cpp
tst/RtpRollingBufferFunctionalityTest.cpp
tst/SdpApiTest.cpp

- N/A
- See the commits tab of this pull request to see all of the pull requests merged into this release.
- Refer to the individual commits for their reasoning.
- Refer to the pull requests for this information.
- CI
- Testing on various platforms (incl. SoC's) for regressions in TTFF, connection success %, across the different network topologies (STUN/TURN), and with various internet connectivity modes (Ethernet, Wifi, 4G LTE/5G).

v1.12.0 Release

---

README.md

* N/A
* The readme has been updated with a sample GStreamer pipeline to generate some sample Opus frames.
* The information did not exist in the readme and it is useful information for users to know to experiment.
* Added a sample command using `audiotestsrc` GStreamer element.
* The new section was placed next to similar spot for the video frames generation.
* Note that I was not able to locate the original music that it was generated from. It is likely the original author used `filesrc` and a local file instead of `audiotestsrc`.
* Locally replaced the sample frames and checked the playback with the [JS …

Add opus sample frame generation GStreamer command to the readme

---

README.md

- N/A
- The readme was updated to have the data channel compile-time configuration.
- I noticed that it was missing when browsing the code.
- https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/blob/v1.12.0/CMakeLists.txt#L20
- Added to the readme.
- Build it locally with this option set to OFF.

Add data channel option to the readme

---

.github/PULL_REQUEST_TEMPLATE.md
.github/workflows/ci.yml
.github/workflows/clang-format.yaml
.github/workflows/codecov.yml
.github/workflows/codeql-analysis.yml
.github/workflows/cross-compilation.yml
.github/workflows/doxygen-gh-pages.yml
.github/workflows/samples.yaml
.github/workflows/sanitizers.yaml

- N/A
- GitHub Actions deprecated the native Ubuntu 20.04 runner. Therefore, we are now using a container-based alternative for legacy builds. [Reference](https://github.blog/changelog/2025-01-15-github-actions-ubuntu-20-runner-image-brownout-dates-and-other-breaking-changes/)
- CI was refactored to use DRY (reducing repetition) since updating the Ubuntu 20.04 GitHub actions image to the Ubuntu 20 ECR image needed to be repeated multiple times. Now, we can more quickly and easily perform future updates for any future deprecations.
- Ubuntu 20 deprecation. Current CI will fail and won't give us confidence that PRs won't break anything.
- Separate the jobs by category into different files
- Pin the …

Upgrade to Ubuntu 22, refactor CI to use DRY, seperate the jobs

---

src/source/PeerConnection/PeerConnection.c
src/source/PeerConnection/Rtcp.c
tst/RtcpFunctionalityTest.cpp

- #2100
- `PeerConnection.c`: Added type casting to prevent integer promotion issues when handling sequence number wraparound in the twccRollingWindowDeletion function.
- `Rtcp.c`: Added type casting to prevent integer promotion issues when handling sequence number wraparound in the updateTwccHashTable function.
- `RtcpFunctionalityTest.cpp`: Added a new test case to validate the behavior of sequence number handling when integer promotion occurs due to UINT16_MAX.
- Integer promotion issue was identified in the handling of sequence numbers during RTP processing by the user of the linked issue. Specifically, when the `lastReportedSeqNum` is exactly `UINT16_MAX`, the subsequent increment can cause incorrect behavior due to …

Fix: Twcc wraparound uint16 promotion case

---

.github/workflows/ci.yml
.github/workflows/codecov.yml
CMake/Dependencies/libawscpp-CMakeLists.txt
CMake/Dependencies/libgtest-CMakeLists.txt
CMake/Dependencies/libkvsCommonLws-CMakeLists.txt
CMake/Dependencies/libmbedtls-CMakeLists.txt
CMake/Dependencies/libopenssl-CMakeLists.txt
CMake/Dependencies/libsrtp-CMakeLists.txt
CMake/Dependencies/libusrsctp-CMakeLists.txt
CMake/Dependencies/libwebsockets-CMakeLists.txt
tst/main.cpp

- Added a script to clean up the old test resources since we hit the channel limit. It appears that the unit tests don't properly clean up their resources. That will be investigated at a later time.
- Set the log level to 7 (silent), and increase the verbosity on retries. This leads to cleaner CI output and quicker to debug what went wrong.
- Add GIT_PROGRESS and GIT_SHALLOW to make it both faster to clone, and to allow to see the cloning progress for larger dependencies like OpenSSL and AWS SDK CPP.
- Avoid getting billed for resources that are unused
- Tests currently fail and block the CI from passing.
- Improve developer experience by having less unimportant logs to load.
- Run the script added in …

Cleaning up stale resources, adjusted logging

---

src/source/Signaling/LwsApiCalls.c
src/source/Signaling/LwsApiCalls.h
src/source/Signaling/Signaling.c

- N/A
- Ability to change LWS logs at runtime, based on KVS log level
- It was previously hard-coded to `LLL_NOTICE | LLL_WARN | LLL_ERR`, so even with LOG_LEVEL_SILENT (7), it will still print logs.
- Here is an example of the logs the PR is referring to:
```
[2025/04/30 20:42:40:4048] N: lws_create_context: LWS: 4.3.3-v4.3.3, NET CLI H1 H2 WS ConMon IPV6-on
[2025/04/30 20:42:40:4053] N: __lws_lc_tag:  ++ [wsi|0|pipe] (1)
[2025/04/30 20:42:40:4053] N: __lws_lc_tag:  ++ [vh|0|netlink] (1)
[2025/04/30 20:42:40:4053] N: __lws_lc_tag:  ++ [vh|1|default||-1] (2)
[2025/04/30 20:42:40:4057] N: __lws_lc_tag:  ++ [wsicli|0|POST/h1/default/kinesisvideo.us-west-2.amazonaws.com] (1)
```
- Created a new function …

Configure LWS logs with KVS log level

---

src/source/Ice/NatBehaviorDiscovery.c

Fix issue where compiler complains on function return type!
- Following error was seen:
`In function 'getNatBehaviorStr': NatBehaviorDiscovery.c:385:1: error: control reaches end of non-void function [-Werror=return-type]`
- Fixed this by returning `NAT_BEHAVIOR_NONE_STR`

Bugfix: getNatBehavior return

---

.github/workflows/ci.yml
.github/workflows/clang-format.yaml
.github/workflows/codecov.yml
.github/workflows/codeql-analysis.yml
.github/workflows/cross-compilation.yml
.github/workflows/doxygen-gh-pages.yml
.github/workflows/samples.yaml
.github/workflows/sanitizers.yaml

- N/A
- Adding 'test-pr-*' as a trigger for the CI.
- Currently, the way we test external contributor contributions is by creating a replica branch in this repository, then creating a dummy pull request to trigger the CI.
- Creating dummy pull requests clutters up the 'merged pull requests' tab.
- This change removes the requirement to create a dummy pull request to trigger the CI. Now, the CI will be automatically triggered on branches in this repository that fit the name: 'test-pr-*', where `*` is anything. 
- Adjusted the CI trigger conditions in the configuration
- Double-checked the spelling of the branch targets
By submitting this pull request, I confirm …

Allow branches named with pattern 'test-pr-*' to trigger the CI

---

CMakeLists.txt
src/include/com/amazonaws/kinesis/video/webrtcclient/Include.h
src/source/Signaling/LwsApiCalls.c
src/source/Signaling/Signaling.c

- We observed the following error message only on Chrome, and only after updating from 135 to 136, with the JS viewer with send video ❌  and send audio ✅ :
```
2025-05-06 18:33:11.823 WARN    lwsWssCallbackRoutine(): Failed in LWS handling routine with 0x5d000028
```
This corresponds to:
```
#define STATUS_SIGNALING_RECEIVED_MESSAGE_LARGER_THAN_MAX_DATA_LEN STATUS_SIGNALING_BASE + 0x00000028
```
- We did not observe the issue when both are enabled.
- Increase the size of the signaling message buffer.
- The buffer was too small. Looking at the release notes, Chrome added support for H.265 and the SDP offer generated by the browser increased in size.
- ~~Doubled~~ ~1.83x'd the size of the constant. We …

Increase the signaling message receive buffer size

---

src/source/PeerConnection/SessionDescription.c

`fmtpForPayloadType` API could return NULL. Trying to print the string if this is NULL is undefined behaviour.
Handled this gracefully.

Handle NULL `fmtp` payload type string in the log

---

src/source/Sctp/Sctp.c

The change fixes following compiler complain:
```
/Users/vikramdattu/work/amazon-kinesis-video-streams-webrtc-sdk-c/src/source/Sctp/Sctp.c: At top level:
/Users/vikramdattu/work/amazon-kinesis-video-streams-webrtc-sdk-c/src/source/Sctp/Sctp.c:213:1: error: multi-line comment [-Werror=comment]
213 | //     /                                                               \
| ^
/Users/vikramdattu/work/amazon-kinesis-video-streams-webrtc-sdk-c/src/source/Sctp/Sctp.c:217:1: error: multi-line comment [-Werror=comment]
217 | //     /                                                               \
| ^
```
`\` Appends next line to current line, leading the above error with multiline-comment.
Fix: Change it to `/`

Sctp.c: Fix `multi-line comment` compiler error

---

src/include/com/amazonaws/kinesis/video/webrtcclient/Include.h
src/source/Ice/Network.c

- N/A
- Skip the hostname parsing optimization for the STUN server
- As an optimization (to skip the getaddrinfo call), we can parse the URL of the TURN servers. However, the STUN server doesn't have the IP address in the URL that we can extract.
- This causes a useless warning log to get printed every time ([example](https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/actions/runs/14790248732/job/41548268381#step:6:295)):
```
2025-05-02 14:54:05.947 INFO    getIpWithHostName(): ICE SERVER Hostname received: stun.kinesisvideo.***.amazonaws.com
2025-05-02 14:54:05.947 WARN    getIpAddrFromDnsHostname(): Received unexpected hostname format: stun.kinesisvideo.***.amazonaws.com
2025-05-02 14:54:05.947 WARN …
```

Skip hostname parsing for stun servers

---

src/source/PeerConnection/SessionDescription.h

Add new default H265 fmtp
· level-id to be 93 (Level 3.1, 720p)
· profile-id to be 1 (Main profile)
Fixed the issue of connection failure caused by incorrect h265 fmtp format.
It has already been tested on  ubuntu、 Amba S5l 、Ingenic T31 、Asrmicro and Rockchip rv1126.

Fix H265 FMTP issue with kvsWebrtcClientViewer

---

src/source/Ice/IceUtils.c
src/source/Ice/IceUtils.h
src/source/Ice/SocketConnection.c

- Did not create an issue for it. I observed the log in my runs, which indicates that the STUN server is unreachable:
```
2025-05-06 00:43:43.406 INFO    getIpWithHostName(): ICE SERVER Hostname received: stun.kinesisvideo.us-west-2.amazonaws.com
2025-05-06 00:43:43.456 PROFILE parseIceServer(): ICE Server address for stun.kinesisvideo.us-west-2.amazonaws.com: 35.165.173.98
...
2025-05-06 00:43:43.526 DEBUG   iceUtilsSendStunPacket(): Sending BINDING_REQUEST to ip:35.165.173.98, port:443
2025-05-06 00:43:43.526 ERROR   socketSendDataWithRetry(): sendto() failed with errno No route to host(65)
2025-05-06 00:43:43.526 DEBUG   socketSendDataWithRetry(): Dest Ip: 35.165.173.98:443. family:1
2025-05-06 00:43:43.526 DEBUG   socketSendDataWithRetry(): hostIpAddr Ip: …
```

Add logs for socket creation fd

---

src/source/PeerConnection/SessionDescription.c

- N/A
- Refactored `serializeSessionDescriptionInit` to eliminate undefined behavior in buffer size calculation logic
- The function previously performed pointer arithmetic on NULL pointers during buffer size calculation phase
- While functionally working, this triggered UndefinedBehaviorSanitizer warnings:
```
2025-05-13 17:26:20.144 INFO    main(): [KVS Viewer] Completed setting local description
2025-05-13 17:26:20.144 INFO    main(): [KVS Viewer] Offer creation successful
2025-05-13 17:26:20.144 INFO    main(): [KVS Viewer] Generating JSON of session description....
/Users/me/Downloads/amazon-kinesis-video-streams-webrtc-sdk-c/src/source/PeerConnection/SessionDescription.c:34:13: runtime error: applying non-zero offset …
```

Fix undefined sanitizer reports for SDP

---

src/include/com/amazonaws/kinesis/video/webrtcclient/Include.h
src/include/com/amazonaws/kinesis/video/webrtcclient/Stats.h
src/source/Ice/IceUtils.h
src/source/Signaling/LwsApiCalls.c
src/source/Signaling/LwsApiCalls.h
tst/IceConfigParsingTest.cpp

- N/A
- Refactored ICE server configuration parsing into a dedicated function `parseIceConfigResponse`
- Fixed potential buffer overflow in string handling
- Added proper buffer length macros to clearly distinguish between string length and buffer size
- Improved error handling for malformed JSON responses
- Fixed incorrect array indexing in password field null termination
- Initially investigated to fix a bug where password field wasn't being properly null-terminated:
```
// Before: Incorrectly using userName instead of password
pSignalingClient->iceConfigs[configCount - 1].userName[MAX_ICE_CONFIG_CREDENTIAL_LEN] = '\0';
```
> [!NOTE]
> This fixes a potential non-null terminated password string. This is not currently an …

Enhance the ice config parser

---

tst/NetworkApiTest.cpp

- N/A
- Unit tests were added for GetIpAddrStr in Network.c
- According to codecov, this method is already covered, however I was unable to locate a test that validated correctness of the out parameter buffer.
- Since we rely on logs heavily during debugging, want to add additional checks to make certain that the IP addresses printed are correct and never accidentally broken in the future.
- Added additional checks for getIpAddrStr, which is a toString for the IP addresses.
- Ran the tests locally, they pass. Source code wasn't touched.
By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms …

Add tests for getIpAddrStr

---

src/source/Include_i.h
src/source/Signaling/LwsApiCalls.c
src/source/Signaling/LwsApiCalls.h
src/source/Signaling/Signaling.c
src/source/Signaling/Signaling.h

- This way, one could write a new CMakeLists.txt, with ApiCalls using different websocket implementation
- One should simply remove existing Signaling.c and LwsApiCalls.c from compilation and add their own
-  Include_i.h and other SIgnaling files modified to contain libwebsockets dependency to C files
- To make it easier to swap the signaling implementation keeping headers re-usable

Refactor Signaling sources to make `Include_i.h` independent of libwebsockets

---

src/source/Signaling/LwsApiCalls.c

Build issue was observed with strict compiler flags for unused label
- Fixed by removing unused `CleanUp` label in `LwsApiCalls.c`

Bugfix: unused label build error observed

---

src/source/Signaling/Signaling.c

- Avoids libwebsockets taking control over using raw fread/nvs APIs
- The SDK, hence, do not need to rely on libwebsockets method
- `libwebsockets` uses file path to read the cacert if the path is provided instead of certificate buffer.
- We lose control over how we want to read the cert
Read the cert before setting up lws config.
- To control how the cert is read.
- Read the cert using readFile API in `Signaling.c`

Read and pass cacert buffer to lws_config instead of path

---

src/source/Signaling/StateMachine.c

- The variable is uint32_t, printing it using llu format specifier is wrong
- Use PRIu32 format specifier for the same

Bugfix: wrong retry count print

---

src/source/PeerConnection/SessionDescription.c
tst/SdpApiTest.cpp

- N/A
- Fixed case-sensitive codec matching in SDP negotiation by replacing `STRSTR` (case-sensitive string contains) with a `STRCASESTR` (case-insensitive string contains) for OPUS codec detection.
- Added unit test `caseInsensitiveCodecMatching_OPUS` to validate the fix
- The SDK was failing to negotiate OPUS audio tracks when remote peers sent SDP offers with capitalized codec names (e.g., `a=rtpmap:111 OPUS/48000/2` instead of `a=rtpmap:111 opus/48000/2`)
- This case-sensitivity issue caused the codec table to miss OPUS payload type mappings, resulting in inactive audio tracks with fake streams instead of proper media negotiation
- Modified `findTransceiversByRemoteDescription()` in …

Ignore case for the Opus codec mime type

---

src/source/Signaling/StateMachine.h

- Slight adjustment to PR #2160
- Add missing header for windows-msvc-openssl and mbedtls-ubuntu-gcc-4-4 CI jobs
- https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/actions/runs/17658125973/job/50263892168
- https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/actions/runs/17658125973/job/50263892050
```
/__w/amazon-kinesis-video-streams-webrtc-sdk-c/amazon-kinesis-video-streams-webrtc-sdk-c/src/source/Signaling/StateMachine.c: In function 'defaultSignalingStateTransitionHook':
/__w/amazon-kinesis-video-streams-webrtc-sdk-c/amazon-kinesis-video-streams-webrtc-sdk-c/src/source/Signaling/StateMachine.c:104: error: expected ')' before 'PRIu32'
```
```
[ 54%] Building C object …
```

Adding inttypes.h for the print specifier
